### ISSUE TITLE
Jumpy playhead

### ISSUE THREAD

**Issue by martybalandis** [bbc/peaks.js#102]
#99 worked from CDN and surprisingly I managed to upgrade from 0.0.X to 0.4.3 within 30min. I have a tiny annoying issue though.

Unlike in 0.0.X version, playhead in the latest version is feels really jumpy. Did I forget something imortant? In the old version it is really smooth, I don't seem to find anything in my code logically that could cause this.

This is the video that shows it: https://dl.dropboxusercontent.com/u/680402/peaks.mp4

This is what my code basically looks like:
            (function(Peaks){
                var options = {
                    container: document.getElementById('waveform-visualiser-container'),
                    mediaElement: document.getElementById('audio'),
                    dataUri: {
                    arraybuffer: datFile
                    },
                    keyboard: false,
                    height: uriParam("height"),
                    zoomWaveformColor: zoomWaveformColor,
                    overviewWaveformColor: overviewWaveformColor,
                    playheadColor: 'rgba(255, 250, 255, 1)'
                };
                Peaks.init(options);
            })(peaks.js);

I am using peaks.js file which I stored on my own server.

**Comment by un-chein-andalou** [comment]
jumpy playhead!

 It starts out jumpy, but if one hits pause then play again - it runs smooth! But goes jumpy again after every seek.

**Comment by chrisn** [comment]
This is fixed in [v0.9.0](https://github.com/bbc/peaks.js/releases/tag/v0.9.0). Feel free to re-open this issue if there's still a problem.
