### ISSUE TITLE
Scrolling the waveform acting strange when zoomed

### ISSUE THREAD

**Issue by pkeuter** [bbc/peaks.js#116]
Love peaks.js, thanks for creating a nice tool like this :-)

I do have a strange problem. When I zoom in or out (which is very slow by the way, probably because of the animation? maybe something to do with #114), and create a region, the upper waveform doesn't scroll anymore, Only the region scrolls. The waveform itself stays at it's original position. Pretty weird behavior.

Also, I'm unable to drag to extend the region in the bottom waveform. Am I doing something wrong? Or  could this be a bug? This looks a lot like #105, I'm on version 0.4.3 by the way.

**Comment by pkeuter** [comment]
Ok, after updating to master, the last problem is gone. My bad :-)

**Comment by chrislatina** [comment]
I'm still seeing this issue. Maybe I need to update waveform-data?

**Comment by ziggythehamster** [comment]
The upper waveform doesn't scroll after a zoom due to a bug (`intermediateData` was never getting nulled, which meant that the waveform would use the old zoom data to show the waveform, not the new zoom data), it's fixed in #118.

**Comment by chrisn** [comment]
Note that you can speed things up by turning off the animation by specifying the `zoomAdapter: 'static'` config option.

**Comment by oncletom** [comment]
@chrisn I guess this issue can be closed now?

**Comment by chrisn** [comment]
This issue is fixed by https://github.com/bbc/peaks.js/commit/054ea9fd615520b188ef6692fed0d7f1bf327e42 , to be published in the next release.
