### ISSUE TITLE
updateSegments function is too slow

### ISSUE THREAD

**Issue by chrisbaume** [bbc/peaks.js#117]
With a realistic number of segments (50 or so) and a realistic recording length (20 mins), the updateSegments function takes over 1.5 seconds to execute, making the browser unusable.

Seems to boil down to the WaveShapedrawFunc in Kinetic which I think does bezier curves. Perhaps at certain zoom levels or certain recording lengths, we could swap to using straight lines?

**Comment by oncletom** [comment]
Or maybe because of #119, which seems to paint once per segment instead of once and for all.

**Comment by chrisn** [comment]
The latest release ([v0.9.0](https://github.com/bbc/peaks.js/releases/tag/v0.9.0)) should improve the rendering speed, as it avoids redrawing segments that are outside the visible range. Closing this issue, but please reopen if performance is still an issue.
