### ISSUE TITLE
Audio out of sync with waveform

### ISSUE THREAD

**Issue by wheredidgogogo** [bbc/peaks.js#133]
When you click around the bottom waveform, the audio plays out of sync with the cursor in the top waveform.

**Comment by wheredidgogogo** [comment]
Just an update to this issue.  Waveforms render correctly with AAC audio files but are out of sync for MP3 files.  I'm not sure if this is an issue in peaks.js or audiowaveform.

**Comment by ffxsam** [comment]
I noticed this too.

**Comment by ffxsam** [comment]
This is even more exaggerated in Firefox. Really terrible delay (the playhead starts moving way before the sound starts). I'll try to see if I can figure out what's going on.

**Comment by jonata** [comment]
Maybe #103 related.

**Comment by vinjegaard** [comment]
I'm experiencing this as well. It is also present on the example here [BBC R&D Peaks.js example page](http://waveform.prototyping.bbc.co.uk/) when skipping around in the first red segment for example.

**Comment by chrisn** [comment]
[audiowaveform](https://github.com/bbc/audiowaveform) v1.1.0 skips information frames in MP3 files, which can cause minor sync issues if you're using .dat or.json waveform data. The [example page](http://waveform.prototyping.bbc.co.uk) uses the latest Peaks.js version, and I'm not seeing sync issues. Closing, but please reopen if there's still a problem. Thanks!

**Comment by BuddyLReno** [comment]
I'm still encountering this issue with MP3s. We're noticing that the playhead is out of sync as soon as you add a segment.  If you play from the beginning of the audio, it's fine.

**Comment by BuddyLReno** [comment]
ok turns out it's the same issue that appears in #239.  Recoding with ffmpeg fixes the issue.
