### ISSUE TITLE
Use in AngularJS

### ISSUE THREAD

**Issue by kokokenada** [bbc/peaks.js#134]
This seems difficult to get going in AngularJS.  I tried the pure JavaScript approach (build locally and include peaks.min.js.  The peaks.js could not be found when I tried the init sample in the readme.  Using requirejs looked like it would need quite a few changes to my app's boot strapping process.  It would be nice if the bower install have me min.js and .js versions of the library that I could simply include and use.

**Comment by oncletom** [comment]
@kokokenada Which tools do you use to build your projects? Maybe we can help configure them rather than changing peaks.js build lifecycle.

**Comment by matixmatix** [comment]
Agree on this one. I'm also having difficulties including this in Ember.

**Comment by chrisn** [comment]
This is fixed in recent versions. There's an Angular example at https://github.com/chrisn/peaksjs-angular-example.
