### ISSUE TITLE
Add custom elements to Segments

### ISSUE THREAD

**Issue by swordsreversed** [bbc/peaks.js#160]
This would be really handy in a case where i had an array with existing IDs i could add them to the segments. The self-generated IDs are not much help tying my data to the segments and tracking by start and end time only works if you never change the the segment, which defeats the whole purpose of having manipulatable segments.

Oddly, I tried adding my own ID using points and it seems to work, not on segments though.

**Comment by oncletom** [comment]
Thanks @swordsreversed, maybe that's just a bug it does not work on segments (or that it works on Points actually).

We wanted to have a nicer and more solid API for Points and Segments, to let users add metadata to them if needed.

Could you eventually provide an example of how you manipulate/update your segments?

Cheers :-)

**Comment by oncletom** [comment]
I just checked and you can assign your own ID to a segment:

```js
peaks.segments.add({
  startTime: peaksInstance.time.getCurrentTime(),
  endTime: peaksInstance.time.getCurrentTime() + 10,
  editable: true,
  id: Date.now()
});
```

More improvements to be found in #87

**Comment by chrisn** [comment]
I'll close this, but please re-open if there's still an issue.
