### ISSUE TITLE
Demo Issue

### ISSUE THREAD

**Issue by Foreweed** [bbc/peaks.js#163]
Hi,

I wonder why when going on your online demo, everything is great (http://waveform.prototyping.bbc.co.uk/), but when I use your index.html file from github, put the correct path to my .mp3 file, and launch peaks with
`<script src="node_modules/peaks.js/peaks.js"></script>`
(after npm install --save it), I get this:
![capture d ecran 2016-11-28 a 15 21 50](https://cloud.githubusercontent.com/assets/20836382/20671890/81792748-b57f-11e6-9c82-b801149e32fd.jpg)

--> No little squares to drag segment in the overview, current zoomview is not green colored on the overview, and when I click the zoom out button, it moves the view 1 minute to the left after zooming out.

**Comment by chrisn** [comment]
The demo page is using an old version of Peaks.js, and the design has changed a bit since then. At some point I think we decided that segments shouldn't be editable in the overview, only in the zoom view, which is why you don't get the handles.

You can change the waveform colours in the overview using the `overviewWaveformColor` and `overviewHighlightRectangleColor` options.

The zoom behaviour you found is a bug.

**Comment by Foreweed** [comment]
Thanks for your answers. However, the 2 params in the options object to init peaks instance you talk about are to choose the total color of the overview waveform (which is grey here), and the other one to choose the color of the rectangle. But my question is how to choose the color of the overview waveform in this rectangle (like in the demo)?
Hope the zoom bug will be corrected soon.

**Comment by chrisn** [comment]
@Foreweed The zoom bug is fixed in `master`, and will be available in the next 0.9 release version.

**Comment by Foreweed** [comment]
Hi,

Ok thanks for your answer.

Regards
CARRILLO Mathieu

**Comment by chrisn** [comment]
I've now published [v0.9.0](https://github.com/bbc/peaks.js/releases/tag/v0.9.0) and updated the [website](http://waveform.prototyping.bbc.co.uk). Please take a look, and feel free to reopen this issue if there's still a problem.
