### ISSUE TITLE
Destroy function

### ISSUE THREAD

**Issue by Foreweed** [bbc/peaks.js#172]
Hi,

It looks like the `instance.destroy()` function no longer exists. Am I right?

**Comment by chrisn** [comment]
It's [still there](https://github.com/bbc/peaks.js/blob/master/src/main.js#L590). What problem are you having?

**Comment by Foreweed** [comment]
I have the following functions:

`var main = {};
function loadPeaksInstance() {
        var options = {...};
    	main.peaksInstance = Peaks.init(options);
}     
        	
function refreshPeaksInstance() {
        main.peaksInstance.destroy();
        loadPeaksInstance();
}`

But when I call the refreshPeaksInstance() function, I get this error: 
TypeError: main.peaksInstance.destroy is not a function

**Comment by chrisn** [comment]
Do you always call `loadPeaksInstance` before calling `refreshPeaksInstance`? If not, you'd need to write:

```javascript
function refreshPeaksInstance() {
  if (main.peaksInstance) {
    main.peaksInstance.destroy();
  }
  loadPeaksInstance();
}
```

**Comment by Foreweed** [comment]
Hi,

Yes indeed I call loadPeaksInstance function, then the waveform show up,
and the user can create a segment, and then delete its content or just crop
it. Then I call the refreshPeaksInstance function with my new audio.
So to say, when I call the refresh function, I'm 100% sure the
main.peaksInstance object exists for the refresh can't be called before
displaying the waveform and interacting with it.

2016-12-11 12:31 GMT+01:00 Chris Needham <notifications@github.com>:

**Comment by Foreweed** [comment]
I got the error with the following code for instance:
`var x = Peaks.init({...});`
`x.destroy();`

**Comment by chrisn** [comment]
Indeed, the build of Peaks.js installed through `npm` does not include the `destroy` method, although it's in the source tree at `v0.5.0`. We'll publish a new release to npm soon.

**Comment by oncletom** [comment]
@Foreweed I have investigated this issue a bit and it seems to be a bug when you try to destroy a peaks instance which has not been able to draw any waveform. As a consequence, the peaks instance's `this.waveform` property is undefined.

How to reproduce:

```js
const p = new Peaks({});
p.destroy();
```

@Foreweed does it sound familiar to you?

**Comment by Foreweed** [comment]
Hi oncletom,

I've been talking with Chris about this issue, and the problem is not `this.waveform` being undefined.
Actually, I'm using the npm version of peaks, and it looks like the destroy function is not in the peaks.js file.
Worse: every destroy functions called indirectly by the `instance.destroy()` function don't exist.
To soluce my problem, here's what I did:
Add this:
```
Peaks.prototype.destroy = function() {
      this.removeAllListeners();
      this.waveform.destroy();
      this.player.destroy();
};
```
Right before `return Peaks` (line ~19611).

Then add this:
```
WaveformOverview.prototype.destroy = function() {
      this.stage.destroy();
      this.stage = null;
};
```
Right before `return WaveformOverview;` (line ~20351).

Then add this:
```
WaveformZoomView.prototype.destroy = function() {
      this.stage.destroy();
      this.stage = null;
};
```
Right before `return WaveformZoomView;` (line ~20607).

Then add this:
```
Waveform.prototype.destroy = function() {
        if (this.waveformOverview) {
              this.waveformOverview.destroy();
        }
        if (this.waveformZoomView) {
              this.waveformZoomView.destroy();
        }
        window.removeEventListener('resize', this.onResize);
        if (this.resizeTimeoutId) {
              clearTimeout(this.resizeTimeoutId);
              this.resizeTimeoutId = null;
        }
};
```
Right before `return Waveform;` (line ~20910).

With those modifications, I only have a options.width == 0 error when refreshing, but it doesn't prevent peaks from working correctly.

Here's my peaks.js modified file: 
[Uploading peaks.js.zip…]()

**Comment by oncletom** [comment]
You are right @Foreweed, I read too quickly. 

@chrisn fixed the issue a few minutes ago and the new `v0.6.0` release should contain the method. The issue was coming from the fact an old version of peaks has been pushed into npm ;-(

**Comment by chrisn** [comment]
Yes, v0.6.0 resolves this issue.
