### ISSUE TITLE
Peaks.init is not a function

### ISSUE THREAD

**Issue by jtolla** [bbc/peaks.js#174]
Probably missing something obvious here. Has anyone else run into this when using an ES6 import?

Ran  `npm install --save peaks.js` in my project. I see it in package.json and it's in node_modules.

I import using `import Peaks from 'peaks.js'` and try to run the sample code. I get the subject error when I try to call Peaks.init(options). And, of course, I can see Peaks.init is exported in the peaks.js core code!

I have other npm imports, like React, working in the same file.

**Comment by jtolla** [comment]
Fixed. I don't think this is related to peaks.js, so I'm going to close - but only seems to work if I give it a path, like `import Peaks from '../../../node_modules/peaks.js/peaks.js';` whereas my other imports, like React, are happy with `import React from 'react'`.

**Comment by oncletom** [comment]
@jtolla I think this is because the `main` declaration in `package.json` aims at `index.js`.

Does it work when you do `import Peaks from '../../../node_modules/peaks.js/index.js'`? Or `import Peaks from '../../../node_modules/peaks.js/src/main.js'`?

**Comment by chrisn** [comment]
This is resolved via #182.
