### ISSUE TITLE
Peaks.init is not a function when importing using webpack

### ISSUE THREAD

**Issue by kme211** [bbc/peaks.js#183]
I am using an [Electron boilerplate](https://github.com/chentsulin/electron-react-boilerplate) which uses webpack to bundle modules and I'm seeing this error in the console:

```
TypeError: Peaks.init is not a function
    at WaveformPeaks.initPeaks (WaveformPeaks.js:53)
    at WaveformPeaks.proxiedMethod (createPrototypeProxy.js:44)
```

I am importing `Peaks` like it shows in the documentation,`import Peaks from 'peaks.js';`, but when I log it into the console, it's just an empty object.

**Comment by craigjohnwright** [comment]
Hello @kme211,

I am currently trying to get this issue resolved with PR #182; I'll try to get it pushed through _asap_. In the meantime you should be able to import peaks with the following:

`import Peaks from '/node_modules/peaks.js/peaks.js';`

Then use the `Peaks` object as the README.md suggests.

**Comment by kme211** [comment]
Thanks so much for your quick reply! I got it working with your help.

**Comment by Grovespaz** [comment]
For those using Typescript experiencing this, use the following line instead:
```
import * as Peaks from '/node_modules/peaks.js/peaks.js';
```

and set allowJs to true in your tsconfig or pass the --allowJs command line flag to tsc

**Comment by chrisn** [comment]
Thanks @craigjohnwright and @Grovespaz for the advice.
