### ISSUE TITLE
Zoom not working while audio is playing

### ISSUE THREAD

**Issue by tyler-workfit** [bbc/peaks.js#184]
Hey all!

I've noticed that zoom does not work while audio is playing.

I can reproduce the behavior in the following locations:
* [the demo page](http://waveform.prototyping.bbc.co.uk/)
* the project repo running on both `master` and `1.x-dev` at localhost:9000
* in our own project

I wanted to confirm others can reproduce this before I start digging in to determine why/fix.

I am running Chrome 56.0.2924.87 (64-bit) on macOS 10.12.1, btw.

Thanks!

**Comment by chrisn** [comment]
Hi, and sorry for the delay in replying. Zooming while playing is disabled (see [here](https://github.com/bbc/peaks.js/blob/master/src/main/views/waveform.zoomview.js#L160)). The main issue that would need addressing is how to reposition the view and the playhead animation after zooming.

**Comment by chrisn** [comment]
This issue is fixed by https://github.com/bbc/peaks.js/commit/054ea9fd615520b188ef6692fed0d7f1bf327e42 , to be published in the next release.
