### ISSUE TITLE
Website seems down

### ISSUE THREAD

**Issue by Grovespaz** [bbc/peaks.js#185]
Hi,

http://waveform.prototyping.bbc.co.uk/ seems down today.
Perhaps it is just a temporary issue but I thought I'd notify you nonetheless.
![image](https://cloud.githubusercontent.com/assets/2829264/24508754/be9931e6-1564-11e7-85f6-58e1bbaaa6c9.png)
(Sorry, it's in Dutch)

Best,
Govert

**Comment by chrisn** [comment]
Thanks for reporting this. We hope to have the site back up soon.

**Comment by chrisn** [comment]
It's back online now. Thanks again.

**Comment by chrisn** [comment]
The website is offline again, sorry. We'll bring it back ASAP.

**Comment by chrisn** [comment]
The website is back, after migrating to a new server and updating the DNS record for waveform.prototyping.bbc.co.uk.
