### ISSUE TITLE
Segment is buggy

### ISSUE THREAD

**Issue by wemiao** [bbc/peaks.js#187]
Hi,
   I am running Google Chrome	57.0.2987.133 (Official Build) (32-bit)
Revision	ec33cd0c06881d919ac0de419d829ad914e0be8f-refs/branch-heads/2987@{#887}

   I am using the peaks.js file from the node_modules/peaks/peaks.js.  Here is my code in my controller:

```javascript
app.controller('audioVizController', ['$scope', '$rootScope', '$timeout' ,'audioViz', 
    '$uibModalInstance', function($scope, $rootScope, $timeout, audioViz, $uibModalInstance) {

    $scope.audioId = "conf_wav_files/"+audioViz.audioId+".wav";

    $scope.close = function () {
        destroyObjects(); // clean up so DOM elements are not duplicated
    };

    var myAudioContext = new AudioContext();

    var destroyObjects = function() {
        myAudioContext.close();
        $uibModalInstance.dismiss({$value: 'cancel'});
    };

    var loadChart = function () {
        (function(Peaks){
            var options = {
                container: document.getElementById('peaks-container'),
                mediaElement: document.getElementById('peaks-audio'),
                audioContext: myAudioContext,
                height: 200,
                segments: [{
                    startTime: 10,
                    endTime: 20,
                    editable: true,
                    labelText: "testinit"
                }]
            };

            var peaksInstance = Peaks.init(options);
            $scope.zoomIn = function() {
                peaksInstance.zoom.zoomIn.bind(peaksInstance); 
            };

            $scope.zoomOut = function() {
                peaksInstance.zoom.zoomOut.bind(peaksInstance);
            };

            $scope.createSegment = function() {
                peaksInstance.segments.add({
                    startTime: peaksInstance.time.getCurrentTime(),
                    endTime: peaksInstance.time.getCurrentTime()+2,
                    editable: true,
                    labelText: "test"
                });
            };

        })(peaks);
    };

    $timeout(loadChart, 0);
}]);
```

Here is the partial code for my modal:

```html
<div id="audio-viz-top" class = "modal-dialog modal-lg">
  <div class="modal-header">
    <button type="button" class="close" ng-click="close()" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Waveform Analysis</h4>
  </div>
  <div class="modal-body">
    <div id="peaks-container" ></div>
    <audio id="peaks-audio" controls="controls">
      <source src={{audioId}} type = "audio/wav">
    </audio>
    <button type="button" class="btn btn-default" ng-click="zoomIn()">Zoom In</button>
    <button type="button" class="btn btn-default" ng-click="zoomOut()">Zoom Out</button>
    <button type="button" class="btn btn-default" ng-click="createSegment()">Create Segment</button>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" ng-click="close()" data-dismiss="modal">Close</button>
  </div>
</div>
```

The audio player works great, but the zoom doesn't work, and when I try to create a segment (or initialize a segment using Peaks.init), it appears like this (see attached png):
![segment bug](https://cloud.githubusercontent.com/assets/16315883/25630916/94ad6a54-2f23-11e7-8392-d7663a715116.PNG)

On the upper graph, the segment markers are correct, but on the lower graph, they are very strange.  The left marker is invisible on the bottom graph when I drag it on the top graph, and somehow appears on the very left.  Also, the "box" in the middle of the marker seems reversed on the bottom graph.  Please advise?

Thanks,
William

**Comment by wemiao** [comment]
I rolled back to peaks.js 0.5.0 (from peaks 0.6.0) and it seems to work at least for the segment part.

**Comment by chrisn** [comment]
Hi William, thanks for your feedback. I'll investigate...

**Comment by wemiao** [comment]
Hi Chris,
   Thanks for the response.

  I wanted to add that zoomIn and zoomOut were fine, I just needed to
execute the functions, mainly the bug was with segments.

Thanks,
William

**Comment by wemiao** [comment]
Thanks for the fix @chrisn!  Will there be a new release of peaks.js in npm?

**Comment by chrisn** [comment]
Sure, I'll reply here when it's done. Thanks for the bug report!

**Comment by chrisn** [comment]
@wemiao Peaks.js v0.7.0 is now available via npm. Please let me know if this works for you.

**Comment by wemiao** [comment]
@chrisn works great so far, thanks for the bug fix!

**Comment by chrisn** [comment]
@wemiao We're always interested to hear how people are using our open source software. If you're willing to share some details about your project, please get in touch. I'm chris dot needham at bbc dot co dot uk. Thanks!
