### ISSUE TITLE
segment.removeById removes 2 segments sometimes

### ISSUE THREAD

**Issue by wemiao** [bbc/peaks.js#188]
I'm not sure why, but it will randomly remove two segments when I have 4-5.  I am certain the IDs are unique (i visually looked several times) so I am not sure why this is happening.

**Comment by chrisn** [comment]
I'll see if I can reproduce this. If you have a specific example or test case, that would be of help.

**Comment by wemiao** [comment]
Sure, I'd be happy to.  Let me show you the before and after snaps:

Before:
![before remove segment](https://cloud.githubusercontent.com/assets/16315883/26009300/0e68bf48-36fd-11e7-8760-6fbefc69145b.PNG)

After:
![after remove segment](https://cloud.githubusercontent.com/assets/16315883/26009301/141c54a4-36fd-11e7-9089-3258efd5b032.PNG)




Here is relevant code I have written:

```javascript
console.log(segment.id);
peaksInstance.segments.removeById(segment.id);
```

And here is an image of my console log:
![segment id on console log](https://cloud.githubusercontent.com/assets/16315883/26009308/1bce0c1a-36fd-11e7-96f5-f514e36b359b.PNG)

Thanks,
William

**Comment by chrisn** [comment]
I tried using this code:
```javascript
peaksInstance.segments.add({ id: '5915eb8dc4f712b349b4315', startTime: 0.0,   endTime: 2.0,   editable: true, labelText: '1' });
peaksInstance.segments.add({ id: '5915eb8dc4f712b349b4317', startTime: 7.26,  endTime: 9.26,  editable: true, labelText: '2' });
peaksInstance.segments.add({ id: '5915eea3c4f712b349b4323', startTime: 19.53, endTime: 21.53, editable: true, labelText: '3' });
peaksInstance.segments.add({ id: '5915eb97c4f712b349b431b', startTime: 27.91, endTime: 29.91, editable: true, labelText: '4' });
peaksInstance.segments.add({ id: '5915eb9bc4f712b349b431d', startTime: 34.69, endTime: 36.69, editable: true, labelText: '5' });
```
followed by:
```javascript
peaksInstance.segments.removeById('5915eea3c4f712b349b4323');
```
but this works as expected, only one segment is removed.

In your example, the segment starting at zero is incorrectly removed, but it's still shown in the table. What does `peaksInstance.segments.getSegments();` return?

**Comment by wemiao** [comment]
Hi Chris,
   You're right, I just tried it today and it seems to work fine.  I think
there may have been a bug in my own code, as I overwrote my entire API last
week to fix some bugs.

   I'll close the issue now, thanks.

William
