### ISSUE TITLE
Implement 2 channels (left, right)

### ISSUE THREAD

**Issue by Bokhanchenko** [bbc/peaks.js#194]
Hello! Your tools is very cool! It helps me in my project and i appreciate you for your work!

I reviewed documentation and can't find can peaks.js display two channels (left and right) not merged in one mono channel?

**Comment by chrisn** [comment]
Peaks.js doesn't currently support a two channel display. A single merged waveform was enough for our use case. I'd be happy to discuss in more detail if you're interested in contributing to the project to add this as a new feature.

**Comment by dannisaur** [comment]
Hi there, I'm also interested in stereo channel display for Peaks.js and would like to contribute it back as a new feature. Please let me know how we can get in touch and discuss further in detail.

**Comment by chrisn** [comment]
Feel free to email, I'm firstname.lastname at bbc.co.uk.

**Comment by Vijayalaxmim** [comment]
Hi Chris, I also need this feature and also be able to mute one channel while playing .Let me know if I can also help

**Comment by chrisn** [comment]
I have updated audiowaveform to support 2 channel waveforms. Next step is to update [waveform-data.js](https://github.com/bbc/waveform-data.js/issues/56), and then Peaks.js itself.

**Comment by chrisn** [comment]
@Vijayalaxmim Muting a single audio channel isn't supported by the `<audio>` or `<video>` elements in HTML. It's likely to be possible to do that using the Web Audio API. Would you be interested in working on an implementation? It could be useful as a stand alone library.

**Comment by chrisn** [comment]
Multi-channel waveform support is added in https://github.com/bbc/peaks.js/commit/2cc06362661c873e9a7394d6ef96e5d2076a0c0f.

**Comment by chrisn** [comment]
Now available in v0.12.0.
