### ISSUE TITLE
Uncaught TypeError: Peaks.init is not a function

### ISSUE THREAD

**Issue by ambhar** [bbc/peaks.js#196]
I am using the cdn version of peak.js for testing index.html which is in the project files but it gives me Uncaught TypeError: Peaks.init is not a function as an error in my browser console.

**Comment by chrisn** [comment]
Thanks for reporting this. We'll investigate, but for now I recommend using `npm install` and using a local copy of peaks.js

**Comment by ambhar** [comment]
Thanks @chrisn It works fine using npm install
