### ISSUE TITLE
Question: Can peaks.js work with SMP

### ISSUE THREAD

**Issue by craigharvi3** [bbc/peaks.js#198]
Hey guys,

This is more of an investigation question rather than an issue.

We're looking into experimenting with waveforms in our UI for CAP (combined audio product - formerly iPlayer Radio & Music).

We use the standard media player for audio and I'm wondering if there's a way to hook peaks.js into the SMP?

Cheers
Craig.

**Comment by chrisn** [comment]
Assuming SMP uses an `<audio>` element under the hood, this should be as simple as calling `Peaks.init()` and passing the object as the `mediaElement` parameter, e.g:
```
var p = Peaks.init({
   container: document.querySelector('#peaks-container'),
   mediaElement: document.querySelector('audio'),
   dataUri: 'path/to/waveform-data/audio.dat'
});
```
Another option is to create an abstracted [`Player`](https://github.com/bbc/peaks.js/blob/master/src/main/player/player.js) object that interfaces to the SMP library.

**Comment by chrisn** [comment]
Happy to collaborate on this, let me know if it's still of interest.
