### ISSUE TITLE
instance.player.seek(seconds) not working properly

### ISSUE THREAD

**Issue by wemiao** [bbc/peaks.js#199]
Hi,
    I have a wav file that is ~44 - 45 seconds long.  When I tried peaksInstance.player.seek(27), the player went to 12 seconds.  I've made a table of test points I collected:

setTime (actualTime) (s)
10 (4)
15 (6)
20 (8)
25 (11)
30 (13)
35 (15)
40 (17)

Sometimes I also get this error (not sure why)

angular.js:14700 TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
    at Player.module.exports.Player.seek (peaks.js:19352)
    at audioVizController.js:193
    at angular.js:20440
    at completeOutstandingRequest (angular.js:6362)
    at angular.js:6642 "Possibly unhandled rejection: {}"

For reference, this is line 193 when that happened (it only happened for some files):

peaksInstance.player.seek(25)

I'd like to add I also tried the console.log(peaksInstance.player.getCurrentTime()).  Here is the full setup:

```
            var peaksInstance;
            var options = {
                container: document.getElementById('peaks-container'),
                mediaElement: document.getElementById('peaks-audio'),
                audioContext: myAudioContext,
                width: 500,
                height: 200,
                waveformBuilderOptions: {
                    scale: 256,
                },
                zoomLevels: [256, 512, 1024, 2048],
                overviewWaveformColor: 'rgba(0,200,200,1)',
                overviewHighlightRectangleColor: 'grey',
                segmentColor: 'rgba(200,20,50,1)',
                randomizeSegmentColor: false,
                segments: $scope.segments 
            };

            $timeout(function(){
                peaksInstance = peaks.init(options);
                peaksInstance.player.seek(25);
                console.log(peaksInstance.player.getCurrentTime());
                if($scope.segments && $scope.segments.length === 10 && $scope.segments[9].labelText.slice(0,5) === 'worst') {
                    console.log(Math.round($scope.segments[9].startTime));
```

This error is returned:
![angular_type_error](https://user-images.githubusercontent.com/16315883/30721390-ad04f130-9ee0-11e7-8773-4a67f60630c7.PNG)

Thanks,
William

**Comment by chrisn** [comment]
Thanks for reporting this. Do you have an example audio file you can share, to help me track down the problem?

The error you're seeing is coming from the HTMLMediaElement, not from Peaks.js, so are you sure your application code always passes valid numbers to `player.seek()`? My guess is that somehow you're passing `undefined`.

This issue highlighted another problem where the playhead position in the zoomable view wasn't being updated after calling `player.seek()`, which I have just pushed a fix for.

One other minor comment: you should use the `peaksInstance.on('peaks.ready')` event to run code when the waveform is loaded and ready.

**Comment by wemiao** [comment]
Hi Chris,
   Thanks for the response.  I have a test file [here](http://new-call-recordings.s3.amazonaws.com/degraded-audio/133001_1_27.wav).

I tried your method of using peaksInstance.on('peaks.ready') like so:

```
            $timeout(function(){
                peaksInstance = peaks.init(options);

                peaksInstance.on('peaks.ready', function() {
                    peaksInstance.player.seek(25);
                    peaksInstance.player.play();
                });

The event never seems to get triggered, I waited about 10-15 seconds.  Do I need to wait longer?

Thanks,
William

**Comment by chrisn** [comment]
I'm not able to reproduce the problems you're having. Seeking within your example WAV file worked fine for me. Which version of Peaks.js are you using? The latest stable release is 0.9.1. The `peaks.ready` event should be triggered after the views are created. If you're using an older release, the event to use would be `segments.ready`, which was replaced by `peaks.ready` in 0.9.0.

**Comment by wemiao** [comment]
It may be I am using an older version.  I'll try to update it and see what happens.

**Comment by wemiao** [comment]
Hi Chris,

I cloned the repo and built the latest version.  I know this is a little off topic, but I don't know if I want to open a new issue just for this.  The seek works correctly now, but the segments only show on the first view now.  i.e. in the new version:

![newest_version](https://user-images.githubusercontent.com/16315883/30888117-b203a8f6-a2d3-11e7-8d50-2d1dd68ec9b8.PNG)

In the old version:
![old_version](https://user-images.githubusercontent.com/16315883/30888119-b7f0e76a-a2d3-11e7-80e7-f9e400fb49fe.PNG)

**Comment by chrisn** [comment]
npm install should bring in the latest version. You can see it published [here](https://www.npmjs.com/package/peaks.js).

```shell
$ mkdir peaksjs-test
$ cd peaksjs-test
$ npm init . -y
Wrote to /home/chrisn/peaksjs-test/package.json:

{
  "name": "peaksjs-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


$ npm install --save peaks.js
peaksjs-test@1.0.0 /home/chrisn/peaksjs-test
└─┬ peaks.js@0.9.1 
  ├── eventemitter2@4.1.2 
  ├── konva@1.6.8 
  └── waveform-data@2.0.1 

npm WARN peaksjs-test@1.0.0 No description
npm WARN peaksjs-test@1.0.0 No repository field.
```
The best way to keep it updated is to use a version specifier like `"^0.9.1"` in your package.json and use `npm update peaks.js`. If you have `"~0.7.0"`, then you won't install any version newer than 0.7.x. You can also use `npm outdated` to check if a new version is available.

```json
  "dependencies": {
    "peaks.js": "^0.9.1"
  }
```

**Comment by wemiao** [comment]
Very good.  Thank you I did not know about npm outdated!  I will close the issue now.
