### ISSUE TITLE
Disabling the zoom view

### ISSUE THREAD

**Issue by loopingrage** [bbc/peaks.js#2]
Wow, I have to say that is a massive contribution! Thanks so much for the great writeup and project. I'd like to use peak.js in one of my project but don't really have a need for the zoom container. There doesn't seem to be an option to disable it though. I'm willing to get my hands dirty and contribute a pull request. Any suggestions / preference on how you'd like to see that implemented?

**Comment by chrisn** [comment]
Resolved in release 0.10.0. Please see https://github.com/bbc/peaks.js/blob/master/demo/overview-waveform.html for an example.
