### ISSUE TITLE
issue with peaks not being removed.

### ISSUE THREAD

**Issue by cmm610** [bbc/peaks.js#200]
You have to remove the points when scrolling on the zoomview and a point is supposed to disappear when it's not in the scope of the zoomview. 

`PointsLayer.prototype._removeInvisiblePoints = function(startTime, endTime) {
    var count = 0;
    
    for (var pointId in this._pointGroups) {
      if (this._pointGroups.hasOwnProperty(pointId)) {
        var point = this._pointGroups[pointId];

        if (!point.point.isVisible(startTime, endTime)) {
          this._removePoint(point.point);
          count++;
        }
      }
    }

    return count;
  };`

Changed point.isVisible to point.point.isVisible
Changed this._removePoint(point) to this._removePoint(point.point)
GREAT LIBRARY, thank you so much for this!

**Comment by chrisn** [comment]
Well spotted, thank you for reporting this!
