### ISSUE TITLE
Memory leak. When is the "ready" event triggered in a peaks instance?

### ISSUE THREAD

**Issue by mwilde345** [bbc/peaks.js#208]
I have code 
`    function addSegments() {
        //TODO: is this causing all the memory leaks....
        peaksInstance.on('peaks.ready', function () {
            peaksInstance.segments.add({
              stuff
            });
          });
          renderSegments(peaksInstance);
        });
      }`

that dynamically adds segments. When I traverse the waveform, moving the zoom bar, this code is continually run. thus I quickly flood the memory with create segments requests. This is giving me leak errors in the browser. 

So, how often is 'ready' triggered so I can figure out how to write this differently?

**Comment by chrisn** [comment]
`peaks.ready` is emitted only once, after calling `Peaks.init()`, when the waveform data has been loaded and the views initialised. Where are you calling your `addSegments()` function from?

**Comment by mwilde345** [comment]
The memory leak is saying there are too many event listeners. These event listeners are added every time I click inside the 'body' element as [written in your example page](https://github.com/bbc/peaks.js/blob/a1a22f9ffd0374fe808ff45c763e625f83160503/index.html#L271)

My mistake for not noticing that. I'm using it in a single page application where the audio is sent from the server and the peaks is initialized afterward on the same page. I will need to figure out how to add click functions for the items populated by [renderSegments](https://github.com/bbc/peaks.js/blob/a1a22f9ffd0374fe808ff45c763e625f83160503/index.html#L180)

**Comment by mwilde345** [comment]
@chrisn Sorry I have to reopen because this is not behaving as if peaks is sending the 'ready' event just once.
I have a peaksInit function on my page:
`var peaksInstance=null;
function peaksInit(peaks){
peaksInstance = peaks.init(options);
peaksInstance.on('peaks.ready', function(){do stuff});
}`

well the 'do stuff' is triggered every time I add a segment or play a segment or drag the tracker over the waveform.
I removed all the body event listeners. This is stemming from the waveform changes.

should I not have a global peaksInstance variable?

**Comment by chrisn** [comment]
If you can send me a complete and minimal code example that demonstrates the problem, I'll be happy to investigate.

**Comment by mwilde345** [comment]
Seems like others have had my same issue. It doesn't stem from peaks, but Web Audio. I found this after testing with a .dat file

https://github.com/katspaugh/wavesurfer.js/issues/326
can you confirm this could cause others trouble as well? perhaps worth mentioning [here](https://github.com/bbc/peaks.js/blob/master/README.md#web-audio-based-waveforms)

**Comment by chrisn** [comment]
Thank you for letting us know about this Web Audio issue, we'll investigate further. Is there still a separate problem with `peaks.ready`?

**Comment by mwilde345** [comment]
@chrisn, peaks.ready is performing normally now. But I can confirm that with the Web Audio issue it was triggered after every interaction with the waveform. Even with a ten second clip i was getting this behavior. It is probably dependent on the CPU and browser specs as well.

**Comment by maitrungduc1410** [comment]
I have the same problem like @mwilde345 too, when I use Angular to build single page application, but now there's only solution is I have to use **dataUri** in the **options** when initialize Peak instead of **audioContext: new AudioContext()**
