### ISSUE TITLE
Is there a way to zoom in amplitude?

### ISSUE THREAD

**Issue by amrfaisal** [bbc/peaks.js#211]
Is there a way to allow users to zoom in waveform amplitude?

**Comment by chrisn** [comment]
At the moment, if you're using precomputed waveform data using `audiowaveform`, there is no way to do this. If instead you're passing an `audioContext` parameter, to use the Web Audio API to produce the waveform data, there is an `amplitude_scale` option. For example, you can set this to 2.0 to double the height of the waveform:

```javascript
waveformBuilderOptions: {
  amplitude_scale: 2.0
}
```

But, this only applies a fixed zoom level, and it's not really part of the documented API, so is likely to change.

A feature that allows the user to dynamically adjust the amplitude zoom would be a good addition. I'd like this feature to be added in a way that allows the zoom level to be set for each waveform view independently, though.

**Comment by amrfaisal** [comment]
Hi @chrisn, Yes, I've made use of this undocumented config, but as you mentioned it doesn't allow to change it after initialization. I had to override a couple of functions to achieve this behavior. It'll be a nice feature to have.

**Comment by aml2610** [comment]
Hi @chrisn, I'd be very interested to know what the status of this enhancement is? I'd like the same functionality as @amrfaisal and whilst the undocumented option is a good start, it'd be nice to have the amplitude zoom change dynamically. Thanks

**Comment by chrisn** [comment]
This is dependent on merging #258, and adding an API to give access to the views. Once we have that, we can add a method to scale the amplitude - which involves changing [`WaveformShape`](https://github.com/bbc/peaks.js/blob/master/src/main/views/waveform-shape.js).

**Comment by chrisn** [comment]
@amrfaisal @aml2610 There is now a `view.setAmplitudeScale()` function that sets the amplitude zoom. Note that the `amplitude_scale` option has been removed, as this was specific to using Web Audio to generate the waveform, whereas `view.setAmplitudeScale()` is generic.
