### ISSUE TITLE
removeAll does not reset segment IDs

### ISSUE THREAD

**Issue by mwilde345** [bbc/peaks.js#212]
This might be a use-case specific issue that I'll have to fix in my own branch, but I am allowing for download and reupload of segment data. I'd like to just get all the segments, store that var, remove all the segments, and then allow for reupload. But I can't add those old segments back into peaks, even after removing all the segments, because I get a 'duplicate id' error. So I go through and remove the id key from each segment object in the array and then I can add them back in just fine and it starts at the id where the previous array left off.

**Comment by chrisn** [comment]
There was a bug in the `removeAll` functions, now fixed. Thanks for reporting this!

**Comment by chrisn** [comment]
@itsIncept Point (and segment) ids that are automatically assigned by Peaks.js are opaque. You shouldn't rely on the specific values. You can assign your own ids if you need to control them.
