### ISSUE TITLE
Typescript type definition

### ISSUE THREAD

**Issue by adrm** [bbc/peaks.js#217]
I am using this library in a Typescript project, and it would be really helpful to have a type definition file for it. I haven't been able to find it myself. Does it exists? Is there any plans to create one?

Thanks.

**Comment by chrisn** [comment]
AFAIK there isn't an existing definition file. This would be a welcome contribution, if you or someone else would like to create it.

**Comment by jeffvandyke** [comment]
Don't forget flow types as well!

**Comment by kdelorey** [comment]
Can this issue be closed now that the @evanlouie contribution has been merged?

**Comment by chrisn** [comment]
Thanks, @kdelorey, I think we can close this.
