### ISSUE TITLE
Is it possible to hide the overview window?

### ISSUE THREAD

**Issue by bfeist** [bbc/peaks.js#222]
I'd like to cause a zoomed window to open and play without the overview being visible. Is this possible via configuration, or will it be a customization? Thanks!

**Comment by chrisn** [comment]
This is a planned feature, yes. See also #2, which requests disabling the zoomable view. I'm going to close this a duplicate, as the solution will allow you to choose which kind of view you want.

**Comment by dpigera** [comment]
@bfeist Not sure if this helps, but removing it on render from the DOM also works:
```
this.$('.overview-container').remove();
```

**Comment by chrisn** [comment]
Resolved in release 0.10.0. Please see https://github.com/bbc/peaks.js/blob/master/demo/zoomable-waveform.html for an example.
