### ISSUE TITLE
seek events not working

### ISSUE THREAD

**Issue by ojczeo** [bbc/peaks.js#223]
`user_seek.overview` and `user_seek.zoomview` not working. Only `user_seek` is working for `overview`. Is there any possibility to listen `zoomview` changes?

**Comment by chrisn** [comment]
You could listen for the `player_seek` event, which tracks the state of the `<audio>` or `<video>` element, so is emitted for both views. Or do you need to specifically track seek events for each view independently?

The `user_seek.overview` and `user_seek.zoomview` events were replaced with a single `user_seek` event, but this is only emitted for the overview waveform. We may not need separate events in the public interface for the user interaction and the media player, so we should consider removing these events from the public interface, instead exposing `player_seek`.

**Comment by ojczeo** [comment]
@chrisn thanks, I just want to watch seeking event in both views. Thanks again!
