### ISSUE TITLE
rerender waveform when height/width of peaks.js container has been changed

### ISSUE THREAD

**Issue by ojczeo** [bbc/peaks.js#224]
I would like to make `peaks.js` more resoponsive - rerender waveform when height/width of peaks container has been changed.

Is there any way to achieve that? for now as I can see there is only way to call 
`peaksInstance.waveform.onResize();` - but it only rerenders width.

**Comment by chrisn** [comment]
It would be great to implement this. I'll take a look when I have time, but will happily accept a pull request!

**Comment by ojczeo** [comment]
@chrisn ok, will try to explore and find solution, and PR as the result

**Comment by chrisn** [comment]
Peaks.js v0.18.0 added a [`view.fitToContainer()`](https://github.com/bbc/peaks.js/blob/master/README.md#viewfittocontainer) method that rerenders the waveform to fit the container's width and height. Feedback is welcome!
