### ISSUE TITLE
Question: what is the format of the json file?

### ISSUE THREAD

**Issue by bfeist** [bbc/peaks.js#226]
Are the numbers in the "data" array individual, or paired per sample?

If I have generated a json file with the following beginning:
{"sample_rate":8000,"samples_per_pixel":256,"bits":8,"length":1858336,"data":[0,0....

can I assume that each number represents the volume level of 256 samples? Thx.

**Comment by chrisn** [comment]
Details of the data format are [here](https://github.com/bbc/audiowaveform/blob/master/doc/DataFormat.md). The numbers are in (minimum, maximum) pairs.
