### ISSUE TITLE
MP3 causing offset, OGG works fine

### ISSUE THREAD

**Issue by martybalandis** [bbc/peaks.js#23]
Based on issue #21 
Hi @oncletom, issue #22 and my one was unrelated but it was an issue as well to me so thank you very much for fixing it. It is a lot better than my workaround solution. The issue I had in #21 remains but I have found out who is the culprit of this is. I basically do 2 files (mp3 and ogg) so it would support more browsers. I got mp3 as priority and ogg as a alternative. The problem is that if you use MP3s it causes an offset and if you use OGGs it is spot on. It seems MP3s fail to load in time or something. I didn't test it on WAVs because I would not use them anyway (files are too big). OGGs, however, do not work on IE and Safari. I can switch priorities aroud of course but IE and Safari users will have an offset.

Any solution to make it work well with MP3s too?

To test simply try any file (with clear beats if possible) with OGG and seek and then try the same with MP3. MP3s seem to be slow in loading though animation starts earlier.

**Comment by oncletom** [comment]
@martybalandis have you tried since then? I suspect this issue has been fixed with #24 and subsequent commits.

**Comment by chrisn** [comment]
[audiowaveform](https://github.com/bbc/audiowaveform) v1.1.0 skips information frames in MP3 files, which can cause minor sync issues if you're using .dat or.json waveform data. The [example page](http://waveform.prototyping.bbc.co.uk) uses the latest Peaks.js version, and I'm not seeing sync issues. Closing, but please reopen if there's still a problem. Thanks!
