### ISSUE TITLE
peaks.js options to split the audio stereo channels in graph. (left audio-right audio )  

### ISSUE THREAD

**Issue by karthiiivgn** [bbc/peaks.js#232]
Hi i cant split the stereo audio channels into two graphs views like wavesurfer (https://wavesurfer-js.org/examples/ ) Split channels feature. please do needful

**Comment by chrisn** [comment]
Closing as duplicate. Please see #194.

**Comment by chrisn** [comment]
This is now available in v0.12.0. Feedback welcome!

**Comment by karthiiivgn** [comment]
Nice feature.... greate
