### ISSUE TITLE
Cursor jumps back to start whenever I click anywhere on the waveform

### ISSUE THREAD

**Issue by josephrocca** [bbc/peaks.js#233]
I've coded up a minimal example that produces this error here:

* Code: https://glitch.com/edit/#!/peak-js-test
* Output: https://peak-js-test.glitch.me

It takes a while to load since it's downloading a video from youtube and it's 18mb, and youtube seems to heavily rate limit the glitch.com severs.

And [here's what happens](https://i.imgur.com/tOe7RHl.mp4).

But the weird thing is, it works fine about 20% of the time.

I did notice that `peakInstance.player._duration` is `NaN`, but this even occurs in that 20% of the time when the library works fine.

![image](https://user-images.githubusercontent.com/1167575/44351711-15786080-a4d5-11e8-9a3b-c3b6b8c0c5b3.png)

Any idea what's happening here? It's version `0.9.12` as you can see from the code.

Might be related to [this issue](https://github.com/bbc/peaks.js/issues/197), except that this isn't a long video - it's just a couple of minutes.

**Comment by chrisn** [comment]
Thanks for reporting this, we'll take a look.

**Comment by chrisn** [comment]
What's happening is that clicking the waveform changes the audio element's `currentTime`, and the visible playhead position is set via the `timeupdate` event. We do this to ensure that the playhead marker is always in sync with the audio element playback position.

In Firefox, if the time we seek to is outside the audio element's `seekable` range, the actual position is set to the end of that range, and not to the position we set. The example below shows me attempting to seek to 14.85 seconds, but the actual position is 0.487619 seconds.

![peaks js-seek](https://user-images.githubusercontent.com/57790/44362165-0f27bb80-a4b8-11e8-830d-872f66a043e5.png)

Chrome behaves differently - the `seekable` range is always (0, 0).

I'll think some more about possible solutions...

**Comment by josephrocca** [comment]
Thanks for getting to this so quickly! That's strange - why doesn't the seekable range work properly in chrome? Should this be reported to crbug?

**Comment by chrisn** [comment]
Seeking works in Chrome despite what the `seekable` range reports, so I need to do some more tests.

**Comment by loretoparisi** [comment]
@chrisn @josephrocca I'm not sure but this seems to be related to

https://stackoverflow.com/questions/53259737/content-range-working-in-safari-but-not-in-chrome

and this forum post I did few days ago

[Chrome bad Range header: Range: bytes=0-](https://groups.google.com/a/chromium.org/forum/#!mydiscussions/net-dev/hYiP5m0K7ZE)

**Comment by chrisn** [comment]
Yes, in my own experiments I've found that the web server hosting the audio / video content must support byte range requests for seeking to work in Peaks.js.

**Comment by loretoparisi** [comment]
@chrisn ok, now it's more clear. Since I'm hosting the Media Server, maybe that is the issue. I cannot see while scrubbing the AJAX request to the server, maybe that's why it does not scrub properly?

**Comment by AntoineGrinn** [comment]
I have the same kind of issue when using the seek method on Chrome v83+.
It works perfectly on Firefox.

**Comment by psam44** [comment]
This issue should be closed, as the reason is the server not returning a "206 Partial Content", as expected for range requests.
See also https://crbug.com/973357.
