### ISSUE TITLE
Can't make it to work with Angular 6 unless I hardcode audio source in the HTML

### ISSUE THREAD

**Issue by heitorb** [bbc/peaks.js#234]
I am trying to use this in an Angular 6 app and I can get it to show only if I hardcode the url for the src, as in:

    <div id="peaks-container"></div>
    <audio>
        <source src="https://s3-us-west-1.amazonaws.com/..../testfile.m4a" type="audio/mp4">
    </audio>

This is the code in the ts file:

       ngAfterViewInit() {

		let myAudioContext = new AudioContext();

		this.p = Peaks.init({
		  container: document.querySelector('#peaks-container'),
		  mediaElement: document.querySelector('audio'),
		  audioContext: myAudioContext,
		});

		this.p.on('peaks.ready', function() {
		  debugger;
		  // do something when the waveform is displayed and ready
		});
	}

However, if I try to use a variable instead, like:

    <div id="peaks-container"></div>
    <audio>
        <source src="{{mediaURL}}" type="audio/mp4">
    </audio>

And "peaks.ready" never gets called.

It doesn't matter in what Angular lyfecycle hook I put the "Peaks.init" code (ngAfterViewInit is one of the last), I always get the same result. Works hardcoded. Not with the variable. BTW, the variable is replaced with the correct url in the final HTML.

Question, is there a way to pass the media URL programmatically via JS during initialization, instead of having to place this in the HTML? If yes that can solve my issue.

If not, has anyone been able to make this work with Angular 2, 4, 5 or 6?

**Comment by chrisn** [comment]
I'm not familiar with Angular, can you share a minimal example project?

**Comment by heitorb** [comment]
Well, before that, do you know if it is possible to add the media URL via Javascript/API instead of in the HTML <audio>? That would solve my problem.

**Comment by chrisn** [comment]
At the moment, it's not possible to do that - you would have to ensure that `Peaks.init` is called after the audio element's `src` has been set. Having an example project will help me be able to design and test a solution. Thanks!

**Comment by heitorb** [comment]
Actually, I've just come up with  a solution for this issue, which involves just adding one line of code to the sample initialization code. So if anyone comes up with this issue, my "fix" below works fine:

Original code in the doc:

    let myAudioContext = new AudioContext();

    this.p = Peaks.init({
	container: document.querySelector('#peaks-container'),
        mediaElement: document.querySelector('audio'),
	audioContext: myAudioContext,
     });

That add source programmatically instead of in the HTML:

    let myAudioContext = new AudioContext();

    //get a reference to the audio element and set the "src" property before calling Peaks.init
    let audioElement = document.querySelector('audio');
    audioElement.src = <variable with the url goes here>;

    this.p = Peaks.init({
	container: document.querySelector('#peaks-container'),
        mediaElement: document.querySelector('audio'),
	audioContext: myAudioContext,
     });

**Comment by chrisn** [comment]
Thanks for posting your solution. I'll close this issue.

**Comment by moimigueldev** [comment]
How were you able to import the files into the .ts file?
