### ISSUE TITLE
The demo should shine right out of the box

### ISSUE THREAD

**Issue by JohnTigue** [bbc/peaks.js#236]
As is a trivial bit of set up needs to be done to get the sample running
```
npm install
npm run build
```
After that the [README.md](https://github.com/bbc/peaks.js#start-using-amd-and-requirejs) is correct in saying that: 
>A working example is provided in index.html.

So, I guess either note the above two steps in README.md, or put a pre-build `peaks.js` in the repo. Otherwise, Peaks does not shine out of the box.

**Comment by JohnTigue** [comment]
It should also be noted that the sample `index.html` must be loaded via `http://...` not `file:` since the latter will cause CORS-based failure. 

Or, go the extra mile and add a devDependencies entry for something like [http-server](https://www.npmjs.com/package/http-server) such that, say, `npm run demo` could do all the rigmarole post `npm install` for them and drop a tire kicker right into the demo in a browser.

**Comment by chrisn** [comment]
Hi John, thanks for your feedback and good suggestions. I'll include in the next release.

**Comment by chrisn** [comment]
@JohnTigue,

> Or, go the extra mile and add a devDependencies entry for something like http-server such that, say, npm run demo could do all the rigmarole post npm install for them and drop a tire kicker right into the demo in a browser.

It wasn't documented in the ReadMe, but `npm start` already does this.
