### ISSUE TITLE
How can I detect when the end of a file is reached?

### ISSUE THREAD

**Issue by heitorb** [bbc/peaks.js#237]
Is there a way to do that? I don't see an event that captures it. Simple reason for this is that I have a play/pause button that toggles state when I click it. When the file gets to the end, I want to be able to detect that so that I can change the button from pause to play.

**Comment by chrisn** [comment]
Peaks.js only partially wraps the audio or video element API, so you can still listen for events directly on the HTMLMediaElement. The [`ended`](https://html.spec.whatwg.org/multipage/media.html#event-media-ended) event should do what you want.
