### ISSUE TITLE
Change function declarations in constructors to use lexical this (i.e. arrow function syntax)

### ISSUE THREAD

**Issue by zachsa** [bbc/peaks.js#242]
Change constructor functions to make use of arrow syntax. I have a click handler in my code that looks like below:

`<Button onClick={() => instance.zoom.zoomIn.call(instance.zoom)}>+</Button>`

Because of lexical this WRT to arrow functions, I figured have to set the this context when calling the `zoomIn` function (it didn't work without setting the `this` context). But. This doesn't work either:

`<Button onClick={function() {instance.zoom.zoomIn() } }>+</Button>`

This code is part of a react component, which is instantiated - so `this` is defined as the react element. Calling `zoomIn()`, `this` will still refer to that element and not `instance.zoom` as it looks like it is supposed to.

**Comment by chrisn** [comment]
Sorry for the delay in replying. Have you found a solution already? I have a React project using Peaks.js, and the following approaches work fine there:
```javascript
<Button onClick={() => { this.instance.zoom.zoomIn() }}>Zoom in</Button>
```
or
```javascript
// in render():
<Button onClick={this.zoomIn}>Zoom in</Button>

zoomIn = () => {
  this.instance.zoom.zoomIn();
};
```

**Comment by zachsa** [comment]
I needed to set the `this` context explicitly.

```
onClick={() => this.state.peaks.zoom.zoomIn.call(this.state.peaks.zoom)}
```

**Comment by chrisn** [comment]
@zachsa Is this still an issue for you?

**Comment by zachsa** [comment]
Hi @chrisn - It's not. I don't mind explicit this context binding, but I think it would be simpler not to have to do this.

**Comment by chrisn** [comment]
I'd be happy to follow up offline - I'd probably need to take a look at your code to see how the approach I mentioned could work in your project.

**Comment by zachsa** [comment]
Okay, thanks. I'd be interested in looking further into this.

In my component I'm doing something like:

```
const ZoomInButton = ({zoomIn}) => 
  <Button
    tooltipDelay={1000}
    tooltipLabel={"Zoom in on the audio"}
    icon 
    onClick={() => zoomIn()}>zoom_in</Button>

class X extends Component {
  getCurrentWaveform = () => this.peaksRefs[this.state.activeAudioIndex]
  componentDidMount() {
    this.peaks = Peaks.init({...})
  }
  zoomIn = () => {
    const waveform = this.getCurrentWaveform()
    waveform.zoom.zoomIn.call(waveform.zoom) 
  }
  render() {
    ... The ref is here somewhere
    ... And somewhere else: <ZoomInButton zoomOut={this.zoomIn} />
  }
}
```

I can't really share the code though, as it doesn't belong to me. Is this enough to go on?

**Comment by zachsa** [comment]
I'm fairly new to React - so it's quite possible that my code is awful

**Comment by chrisn** [comment]
I'm not quite seeing what's wrong here. I think that this code should work:

```javascript
zoomIn = () => {
  this.peaks.zoom.zoomIn();
}
```

So the difference may be in what's in your `this.peaksRefs` array.

Feel free to email chris dot needham at bbc.co.uk to follow up.

**Comment by zachsa** [comment]
Thank you @chrisn. I've taken down your email address to follow up with you

**Comment by zachsa** [comment]
Apologies for the delay - I've been trying to replicate what I (thought I) saw when I was working on this previously. I haven't been able to though. I'm not exactly sure what the problem was and why an explicit `this` binding solved it. 

Actually... thinking about this a bit. I'm not sure that it's possible for a method defined on a prototype object to receive the wrong `this` context when executed? I must have been confused elsewhere.
