### ISSUE TITLE
Built in event for when playhead hits a point/segment ?

### ISSUE THREAD

**Issue by peet-j** [bbc/peaks.js#243]
I'd like to be able to play a sound when the play head hits a point and/or segment.
Is it possible to subscribe to a built in event for this or will it require a custom one?

thanks

**Comment by chrisn** [comment]
We don't currently have such events, but it's a good use case. To implement this, we'd need to:
* Add a `player_time_update` event handler to trigger events on passing over a point, and entering/leaving a segment
* Store points and segments in time order, to allow efficient lookup by time

If you're interested in working on this, please let me know.
