### ISSUE TITLE
Touch events not working on Android

### ISSUE THREAD

**Issue by rfrei** [bbc/peaks.js#248]
Both zoom-container and overview-container does not react to touch or mouse events on Android in Google Chrome and Firefox.

**Comment by BuddyLReno** [comment]
Would love to figure this out as well. Looking to make a clip creator in my web app.

**Comment by chrisn** [comment]
I agree. It sounds like there's two separate things here: an issue with mouse events on Android Chrome and Firefox, and touch events, which aren't currently implemented.

**Comment by BuddyLReno** [comment]
I'm trying to tech spike touch events right now. I'm hoping it's not too tough to simply map the touch events to the same events that are currently attached to the mouse events.

**Comment by chrisn** [comment]
Sounds great, please take a look at `src/main/views/mousedraghandler.js`. There's also mouse handling code for point and segment markers in `src/main/waveform/waveform.mixins.js`

**Comment by BuddyLReno** [comment]
Good progress so far! 

- The events for touchstart and touchend have been mapped to their respective mouse equivalents. 
- Converted positioning for respective events to their touch equivalents.

With these changes I've been able to get the cursor moving on a mobile platform, both iOS and Android browsers. Safari has this weird flickering thing happening when you touch the canvas but I'm going to worry about that later.

Here's the commit on the fork I'm working with: https://github.com/lampo/peaks.js/commit/e4233757499982d729576c5afe985f6c76dce213

First commit is pretty simple. Took awhile because I had react dev tools crashing the browser during the `touchstart` event somewhere. Disabled that and quickly figured out the rest.

This should effectively convert `src/main/views/mousedraghandler.js`.  Taking a look at `src/main/waveform/waveform.mixins.js` now.

**Comment by rfrei** [comment]
That's awesome.

**Comment by chrisn** [comment]
Looks good so far! Peaks.js uses Konva for canvas rendering, so [this page](https://konvajs.github.io/docs/events/Mobile_Events.html) should be helpful.

**Comment by BuddyLReno** [comment]
Thanks! Should hopefully make some more excellent progress tomorrow.

**Comment by chrisn** [comment]
I notice you're committing to `master` branch, if you plan to send a pull request, would you mind moving your commits to a feature branch, please? It makes handling contributions much easier, I wouldn't want our master branches to diverge. Thanks!

**Comment by BuddyLReno** [comment]
Sure thing! I'll move the commits over as soon as I get into the office. 👍

**Comment by rfrei** [comment]
I just added additional handling for touchmove events so I can drag the waveform on mobile touch screens https://github.com/rfrei/peaks.js/commit/b7728d4eba3645f4c9be65acdc95d50185bd38fa
But there is a strange behavior. When I move the zoom-containers waveform container, it is sometimes not redrawn. Look here: https://github.com/rfrei/radiofrei/blob/master/peaksjs.gif
This is the unchanged index.html example captured in chrome developer tools device mode but it is exactly the same behavior on real Android Devices.
Any Idea?

**Comment by BuddyLReno** [comment]
@rfrei I wasn't able to get that far today. Had an expedite so I was unable to look further into this. I'll looking at it again on Wednesday next week. Have you taken a look at the other file that @chrisn mentioned? `src/main/waveform/waveform.mixins.js` Also, check out the Konva docs that he mentioned earlier as well: https://konvajs.github.io/docs/events/Mobile_Events.html

**Comment by rfrei** [comment]
@BuddyLReno Yes I looked at the code in src/main/waveform/waveform.mixins.js but it is only for point and segment markers. I'll keep looking at it, thanks so far.

**Comment by rfrei** [comment]
The issue that mouse events are not working on Android is Konva related, I created an issue for Konva https://github.com/konvajs/konva/issues/516

**Comment by rfrei** [comment]
Update:
> But there is a strange behavior. When I move the zoom-containers waveform, it is sometimes not redrawn.

After get konva mouse events working on my tablet with attached mouse it turns out that the redraw problem only occurs on touch events but not mouse events. If I convert to Integer the problem is gone.

**Comment by rfrei** [comment]
created pull request https://github.com/bbc/peaks.js/pull/249

**Comment by rfrei** [comment]
merged

**Comment by BuddyLReno** [comment]
@rfrei Thanks for working on this! Sorry I couldn't get back to it soon enough to help.

**Comment by rfrei** [comment]
@BuddyLReno you helped a lot! Thanks for hinting the start point.

**Comment by BuddyLReno** [comment]
No problem man! Let's build some cool stuff! 👊
