### ISSUE TITLE
Add a 'segment.onmouseenter' event

### ISSUE THREAD

**Issue by zachsa** [bbc/peaks.js#250]
I see there is an open issue for a new Markers API (https://github.com/bbc/peaks.js/issues/87) that, amongst other things, will allow for a `segments.click` event. 

Until this is implemented, is there anyway of 'selecting' a segment, either via clicking/onmouseenter/or something else?

**Comment by chrisn** [comment]
Right now there's no way to mark a segment as selected. There is already `mouseenter` / `mouseleave` handling, which responds by showing / hiding the segment label text. Is it enough to simply make this event part of the Peaks.js API, then handle selection at the application level?

Or maybe we need a more complete selection implementation within Peaks.js? In this case, there are some things to think about:
- How does a segment become selected: click or mouseenter event, API call?
- What if there are overlapping segments?
- Do we allow multiple segments to be selected?
- What should the appearance of selected segments be?
- If we add selected segments, for consistency we should do the same for points.

I suggest working on this separately from #87, which probably won't be implemented as proposed.

**Comment by zachsa** [comment]
Hi @chrisn - working on #247, I saw that it would be easy enough to add this functionality?

I see that a bunch of event handlers are setup in SegmentsLayer.prototype._createSegmentGroup(). It takes a few lines of code to emit events when a segment is interacted with. i.e.:
```
segmentGroup.waveformShape.on('click',  function(event) {
  ...
  self._peaks.emit('segments.clicked', event.target.segment) // I see that the clicked segment is identifiable
}
```
And emitting similar events in the mouseenter and mouseleave event handlers in this same function.

I think this works well in conjunction with being able to update segments, and it seems like a straightforward bit of work?

Please let me know if you think this is worth tackling!

**Comment by chrisn** [comment]
This is a good idea, we have similar events for point markers, see documentation [here](https://github.com/bbc/peaks.js#points). You're very welcome to add this if you want to. I really appreciate the work you're doing :-)

**Comment by zachsa** [comment]
Thank you very much for helping me with this @chrisn - It has been excellent experience and I appreciate the opportunity!

I found that the this was quite easy to do - https://github.com/zachsa/peaks.js/commit/2273fea3ab9dc31236a54e4842755d42eac03839. However this may or may not be the 'right' approach.

If I am on track, then I'll make another pull request.

**Comment by chrisn** [comment]
Looks good to me. To complete this, we'd need to update `InstanceEvents` in [peaks.d.ts](https://github.com/bbc/peaks.js/blob/master/peaks.js.d.ts#L97), and add documentation to the [ReadMe](https://github.com/bbc/peaks.js/blob/master/README.md#segments).

**Comment by zachsa** [comment]
> Looks good to me. To complete this, we'd need to update `InstanceEvents` in [peaks.d.ts](https://github.com/bbc/peaks.js/blob/master/peaks.js.d.ts#L97), and add documentation to the [ReadMe](https://github.com/bbc/peaks.js/blob/master/README.md#segments).

both done

**Comment by chrisn** [comment]
I have merged #261. But this reminds me of something I don't really like about the mouse event behaviour for segments. These events are only triggered when the user hovers/clicks the mouse directly over the waveform image. I'd like to come up with a way to make the active region for these events bigger, possibly as a rectangular region around each segment. What do you think?

**Comment by zachsa** [comment]
I used to use Logic/Cubase/etc., so my first experience with Peaks.js was that I expected the entire 'rectangular' space to be the 'waveform'.

Since the label appears/disappears when you hover over a segment it's intuitive. But I think it would be generally better if the entire space between markers was considered a 'segment'.

And more generally, I think the entire rectangular canvas space should count as the waveform.

**Comment by zachsa** [comment]
Actually... When I first saw Peaks it reminded me of a DAW workspace. Is there any intention of providing a suite of tools that could allow for arranging sound in the same way a DAW does? Ideas off the top of my head:

Segments could:

- Be stretched/shrunk (slowdown/speedup audio)
- Have fades and crossfades applied to their ends
- Could have pitch/volume/etc 'envelopes'

Could Peaks.js support these things?

**Comment by chrisn** [comment]
> But I think it would be generally better if the entire space between markers was considered a 'segment'.

I agree. I'll raise this as a separate issue, so we can close this one.

> Segments could:
> * Be stretched/shrunk (slowdown/speedup audio)
> * Have fades and crossfades applied to their ends
> * Could have pitch/volume/etc 'envelopes'
> Could Peaks.js support these things?

In principle it could, but Peaks.js was designed mainly for annotating audio clips, not really with the intent of building an audio editor.  What you're describing would need a much more powerful playback engine, which should be feasible using the Web Audio API. Anyone interested in working on an audio editor is welcome to use Peaks.js as a basis.

**Comment by zachsa** [comment]
Issue opened here: https://github.com/bbc/peaks.js/issues/262
