### ISSUE TITLE
peaks.player.getDuration() returns Infinity

### ISSUE THREAD

**Issue by zachsa** [bbc/peaks.js#255]
I'm streaming audio to the client to use with Peaks.JS. Is there anyway to get the length of a clip for streamed audio?

I didn't even know that `Infinity` was a valid number type in JavaScript

**Comment by chrisn** [comment]
Peaks.js doesn't currently support streaming audio, as we don't have a way to generate the waveform on the fly. How are you creating the clips? `getDuration()` simply returns the duration from the underlying `<audio>` or `<video>` element. This will be `Infinity` for streaming media - see the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration).

**Comment by zachsa** [comment]
Thanks @chrisn - technically I'm piping an audio file from a server to the client through a node.js server. So while this is a stream (I think) there is a definite start and end to the audio file.

However, the waveform is drawing successfully. why is this?

**Comment by zachsa** [comment]
I found that Chrome was making multiple requests for a single audio file, and including a range header. I have found that if I support the range header in my API explicitly that `<audio/>` element worked as expected.
