### ISSUE TITLE
use while recording audio

### ISSUE THREAD

**Issue by greaber** [bbc/peaks.js#256]
Hello! I just stumbled on peaks.js, and it looks really nice.  However, in my application, the user is recording audio on their computer.  I would like to show a scrolling waveform like when you record in Pro Tools or Audacity.  Can peaks.js do this?  (Or, if not, is there another tool you recommend?  The main thing is just to give the user some feedback about whether they are either too quiet or clipping.)

**Comment by chrisn** [comment]
This is a really interesting use case, but sadly one that Peaks.js doesn't support at the moment. Related previous discussion: https://github.com/bbc/peaks.js/issues/189.

**Comment by greaber** [comment]
OK, that's a pity, thanks for the quick response!
