### ISSUE TITLE
What method can we use to draw the whole waveform?

### ISSUE THREAD

**Issue by ChaoshengZhang** [bbc/peaks.js#257]
What method can we use to draw the whole waveform?

**Comment by chrisn** [comment]
Hi, @ChaoshengZhang, can do describe what you want to do in more detail?

**Comment by ChaoshengZhang** [comment]
I want to know how to draw the whole audio waveform directly. I hope you can help me answer the questions. Thank you. Is it the HTML 5 API or something else, I hope you can provide some ideas. Thank you.
我想知道，通过什么方法直接绘制整个音频的波形图的，希望你们帮我解答疑惑，谢谢你。是html5的api还是什么其他的，希望你可以提供一下思路。谢谢你。

**Comment by chrisn** [comment]
I recommend that you look at our [waveform-data.js](https://github.com/bbc/waveform-data.js) module. The ReadMe has some [example code](https://github.com/bbc/waveform-data.js#drawing-in-canvas) that shows how to draw a waveform using the HTML Canvas API.
