### ISSUE TITLE
Peaks.js renders wrong waveform when audio src is changed

### ISSUE THREAD

**Issue by gsultano** [bbc/peaks.js#259]
I'm having a problem using Peaks.js.
When Peaks get initialized the first time it renders properly waveform associated to src audio. Troubles begins when I try lo load another audio and render it's waveform because I found a weird behaviour. Peaks.js renders the waveform of previous audio src.
So for exampe I have got 3 audio files
When I load the first one -> Peaks renders it's waveform and it's ok.
When I load the second one-> Peaks renders waveform of the first one.
When I load the third one -> Peaks renders waveform of the second one.
And so on.

The audio file is provided from input of typefile and passed to the function via FileReader

Code:

```javascript
//Get waveform div element
var waveformContainer = document.getElementById('waveform') as HTMLDivElement;        
//Clean inner html if there was rendered a previous waveform
waveformContainer.innerHTML = "";
//Get audio element
var audioElement = document.getElementById('audio') as HTMLAudioElement;
//If there was a previous instance of peaks, destroy it
if(this.peaks != null){
    this.peaks.destroy();
}
//Create audio from file (typeof File)
var audioObjURL = URL.createObjectURL(file);
//Set the audio src
audioElement.src = audioObjURL;

//Options

var options = {
  /** REQUIRED OPTIONS **/
  // Containing element
  container: waveformContainer,
  audioContext: new AudioContext(),
  logger: console.error.bind(console),
  height: 50,
  zoomLevels: [512],
  keyboard: false,
  nudgeIncrement: 0.01,
  inMarkerColor: '#a0a0a0',
  outMarkerColor: '#a0a0a0',
  zoomWaveformColor: 'rgba(0, 225, 128, 0)',
  overviewWaveformColor: 'rgba(255,120,50,1)',
  overviewHighlightRectangleColor: 'transparent',
  segmentColor: 'rgba(255, 161, 39, 1)',
  playheadColor: 'rgba(0, 0, 0, 1)',
  playheadTextColor: '#aaa',
  showPlayheadTime: false,
  pointMarkerColor: '#FF0000',
  axisGridlineColor: '#ccc',
  axisLabelColor: '#aaa',
  //randomizeSegmentColor: true,
  zoomAdapter: 'animated',          
}

//Create new Peaks instance
this.peaks = Peaks.init(options);
```

**Comment by chrisn** [comment]
Some notes from an initial investigation: Peaks.js uses the media element's `currentSrc` attribute to obtain the URL of the audio (https://github.com/bbc/peaks.js/blob/master/src/main/waveform/waveform.core.js#L175). When you change the `src` attribute, you have to wait until the `currentSrc` is updated, after a `canplay` event is fired. So the solution is to either modify `_buildWaveformDataUsingWebAudio` to use `src`, or wait for `canplay`.

**Comment by chrisn** [comment]
See `setSource()` in v0.11.0 and later.
