### ISSUE TITLE
Only the actual waveform between segment markers is seen as a segment

### ISSUE THREAD

**Issue by zachsa** [bbc/peaks.js#262]
When creating a segment. The 'label' is only seen when a user hovers on the segment wave 'marks'. I think it would be better if a 'segment' encompassed all the space between markers.

This would also make the segment mouseenter, mouseleave, click events emitted in a more obvious way. I sometimes click between the markers, but not on the actual waveform and wonder why the click handler isn't working (the actual waveform needs to be clicked).

**Comment by chrisn** [comment]
It looks like we may be able to use a `hitFunc` in the `WaveformShape` for this, see the [Konva.js docs](https://konvajs.org/docs/events/Custom_Hit_Region.html).

**Comment by chrisn** [comment]
This is now fixed in `master` and will be in the next release version.
