### ISSUE TITLE
Toggle waveform containers visibility

### ISSUE THREAD

**Issue by zachsa** [bbc/peaks.js#263]
With pull request https://github.com/bbc/peaks.js/pull/258, it's now possible to configure which waveform container are show (the zoomed container or the regular container).

I think it might also be nice if:

1. It were possible to toggle visibility of the containers
2. It were possible to render the two containers in separate locations (vs always having one on top of the other)

**Comment by chrisn** [comment]
To toggle the zoomview, you can now do:

```javascript
function toggleZoomview() {
  const zoomview = instance.views.getView('zoomview');
  const container = document.getElementById('zoomview-container');

  if (zoomview) {
    instance.views.destroyZoomview();

    container.style.display = 'none';
  }
  else {
    container.style.display = 'block';
    instance.views.createZoomview(container);
  }
}
```

(and similar for the overview waveform)
