### ISSUE TITLE
StartTime format

### ISSUE THREAD

**Issue by Akash1842** [bbc/peaks.js#264]
Hello guys,
Good Evening...
I want to get the startTime value from waveform but in specific format(for eg. HH:MM:Seconds).
Right now i am getting only integer value

**Comment by chrisn** [comment]
There's an [internal method](https://github.com/bbc/peaks.js/blob/master/src/main/waveform/waveform.utils.js#L42) that we use to format times, but this is not exposed by the API. Or you could use a library such as [moment](https://momentjs.com/).
