### ISSUE TITLE
Bug: Memory leak detected when drag too often

### ISSUE THREAD

**Issue by sfilata** [bbc/peaks.js#269]
Hello ~
The bug is described in title.Error stack is shown in the image below.
![1562576051](https://user-images.githubusercontent.com/12068103/60797389-c0534500-a1a1-11e9-8247-1eede21bdf98.png)
Thanks

**Comment by chrisn** [comment]
Can you please provide more detail on what actions trigger this error? I have not been able to reproduce it yet, using the demo pages in the project (use `npm start` and open http://localhost:8080). Thanks!

**Comment by sfilata** [comment]
It's a bug in verson 0.9.10. When I upgrade to version 0.9.14, it works normally. Thanks a lot !
