### ISSUE TITLE
The new segment.update() doesn't render waveform properly

### ISSUE THREAD

**Issue by peanut11** [bbc/peaks.js#270]
The new update() function is really convenient for most of my use cases. However, when I use the `segments.update()` function to update segment `startTime` and `endTime`, the segment editable markers disappear even though `editable` attribute is still set to `True`. Any tips to overcome this other than removing and adding the segment again?

**Comment by chrisn** [comment]
Thanks for letting us know. This sounds like a bug, so I'll investigate.

**Comment by chrisn** [comment]
I have just released [v0.10.1](https://github.com/bbc/peaks.js/releases/tag/v0.10.1), which fixes this issue. Thanks again.
