### ISSUE TITLE
getDuration sometimes returns NaN

### ISSUE THREAD

**Issue by jodonnell** [bbc/peaks.js#280]
```        Peaks.init(options, (err, peaks) => {
            if (err)
                return;
            setPeaksInstance(peaks);
            console.log(peaks.player.getDuration());
        });
```
if i refresh my page sometimes it returns the duration and other times NaN.

**Comment by chrisn** [comment]
`getDuration` simply returns the value of the `duration` attribute from the underlying media element. `NaN` indicates that the media data is unavailable (see https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration).

**Comment by jodonnell** [comment]
Hi Chris, 

Does that imply that if I need the duration for display I should use the durationchange event handler on the media element tag?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/durationchange_event

Thank you,
Jacob

**Comment by jodonnell** [comment]
`<audio onDurationChange={(e) => { console.log(e.currentTarget.duration); }}>`

does in fact work, thank you
