### ISSUE TITLE
waveform rendering performance

### ISSUE THREAD

**Issue by leeoniya** [bbc/peaks.js#282]
Hi @chrisn,

I'm coding a little project [1] right now that may be of interest to you. I'm looking for real-world applications that can benefit from a high-performing line plotting lib and `peaks.js` seems like a great candidate. It may be interesting to collaborate and maybe improve `peak.js` performance as well. Ping me if interested.

Cheers!

[1] https://github.com/leeoniya/uPlot

**Comment by chrisn** [comment]
Many thanks for the pointer, I'll take a look!
