### ISSUE TITLE
Remove Zoomview

### ISSUE THREAD

**Issue by spruterkex** [bbc/peaks.js#283]
Hi!
Thank you for your great work! 
Is there a way to dynamically remove the zoomview after peaks is initiated?

**Comment by chrisn** [comment]
Thanks! There isn't currently an API method for that, although should be easy enough to add. For now, you'd have to hide the zoomview's container element.

**Comment by spruterkex** [comment]
Thank you for your quick response! 

Yes that is how I do it now, the only problem (for me) then is that the highlight on the overview still is visible. If hiding the zoomview is the way, is there a way to change the highlight (maybe the color) after peaks is initiated? (I'm sorry of it's unorthodox to ask these questions here, I'm a new at GitHub).

**Comment by chrisn** [comment]
Feel free to ask questions! There is a `view.destroy()` method, but this is not part of the public API, and would need to change to support your use case - e.g., to remove the highlight from the overview waveform. Then you'd be able to write:

```javascript
const zoomView = peaksInstance.views.getView('zoomview');
zoomView.destroy();
// And now hide the container element
```

**Comment by chrisn** [comment]
By the way, if you never need the zoomview then you can tell Peaks.js to only create the overview waveform (see https://github.com/bbc/peaks.js/blob/master/demo/overview-waveform.html).

**Comment by chrisn** [comment]
To remove the zoomview, you can now do:

```javascript
instance.views.destroyZoomview();

const container = document.getElementById('zoomview-container');
container.style.display = 'none';
```

(and similar for the overview waveform)
