### ISSUE TITLE
Text appears behind waveform

### ISSUE THREAD

**Issue by jodonnell** [bbc/peaks.js#285]
![Screen Shot 2019-11-04 at 12 47 13 PM](https://user-images.githubusercontent.com/217747/68144260-43db3380-ff01-11e9-96c3-8ca60fe8253a.png)

in the screenshot you can see the axis text marker is hiding behind the waveform.

i went into the code, in WaveformOverview and swapped these two lines (the below is after swapping)
```
        self._createWaveform();
        self._axis = new WaveformAxis(self, self._waveformLayer, peaks.options);
```
after doing that i see
![Screen Shot 2019-11-04 at 12 48 36 PM](https://user-images.githubusercontent.com/217747/68144340-7553ff00-ff01-11e9-8036-5859f78ae689.png)

is there a way of doing this without editing the source?

**Comment by chrisn** [comment]
Thanks for reporting this. I think it's a bug, the second screenshot looks right to me.

**Comment by jodonnell** [comment]
if the solution is simply swapping the createWaveform and new WaveformAxis lines in both the WaveformOverview and WaveformZoomView, i'd be happy to make a PR for that.

**Comment by chrisn** [comment]
Yes, it seems the z-order of the shapes is the order they are added into the Layer, so swapping those lines should work. I'll happily merge a PR, thanks!

**Comment by jodonnell** [comment]
so i think whats going on is i'm doing this
            overviewWaveformColor: '#a8a0a0',
by default this waveform color has opacity on it, so you can see through the waveform and see the text labels.

i tried swapping these lines of code and the labels disappeared completely, which is fixed by after initing calling view.setAmplitudeScale(1), so i'm not sure whats going on with that.

Personally i'm happy setting the opacity on the waveform, so i'm okay with closing this.

**Comment by chrisn** [comment]
Let's leave this open for now, I'll take a look to see if anything needs changing.

**Comment by jodonnell** [comment]
👍

**Comment by jodonnell** [comment]
oh dang, thanks!
