### ISSUE TITLE
Overview highlight doesn't look so good shrunk

### ISSUE THREAD

**Issue by jodonnell** [bbc/peaks.js#287]
When I use css to shrink overview bar to 50px the highlight looks a little too stubby.

<img width="91" alt="Screen Shot 2019-11-05 at 9 27 55 PM" src="https://user-images.githubusercontent.com/217747/68263124-2f875b80-0013-11ea-8c7c-dac8489da750.png">

I found in the code 
```
    this._highlightRect = new Konva.Rect({
      startOffset: 0,
      y: 11,
      width: endOffset - startOffset,
      stroke: this._options.overviewHighlightRectangleColor,
      strokeWidth: 1,
      height: this._height - (11 * 2),
      fill: this._options.overviewHighlightRectangleColor,
      opacity: 0.3,
      cornerRadius: 2
    });
```
this looks pretty good for the standard 200px but not so great for the smaller size.

I'd be happy to attempt a PR here, options is in scope already so I could easily make an override, I'm not sure if i would just do overviewHighlightRectangleY and overviewHighlightRectangleHeight and the presence of either one would override the default or maybe just overviewHighlightRectangleHeight and if thats found turn the y to 0.

Thank you for all the help, I suspect this will be the last issue that I have.

**Comment by chrisn** [comment]
Maybe the option should be  `overviewHighlightRectangleOffset` which sets the distance from the top and bottom (default 11 for backwards compatibility)?

While we're here, I'm thinking about renaming `overviewHighlightRectangle` to simply `overviewHighlight` (with a console message for people currently using `overviewHighlightRectangleColor`).

**Comment by jodonnell** [comment]
👍 
https://github.com/bbc/peaks.js/pull/288

**Comment by chrisn** [comment]
I think this is all OK now, published in v0.14.4.

**Comment by jodonnell** [comment]
great, thanks

**Comment by chrisn** [comment]
Thank you too! :-)
