### ISSUE TITLE
Segment API is not working

### ISSUE THREAD

**Issue by ghost** [bbc/peaks.js#29]
console.log(peaks.segments.getSegments());
returns undefined.  (TypeError: api.waveform.segments is undefined)

Same is with: peaks.segments.addSegment(startTime, endTime, editable, labelText)

**Comment by dafyk** [comment]
Found this issue in latest dev version. `addSegment` is not defined and quick look to `console.log(p.segments)` shows `getSegments: function, add: function, remove: function, removeById: function, removeByTime: function…}`
Using `add` insted of `addSegment` works.
