### ISSUE TITLE
Add double click event

### ISSUE THREAD

**Issue by mikearmstrong1** [bbc/peaks.js#293]
I would like to be able to add a point on double click. I think this would be a more intuitive user experience compared to clicking on the wave then clicking a button.

Is this already possible and I missed it?

**Comment by chrisn** [comment]
This isn't currently possible.. As people have different use cases, I wouldn't want to bind double click to a specific action. Perhaps the best way to handle this is to add events so that your application can decide how to respond.

**Comment by mikearmstrong1** [comment]
Thanks for the response. That was the other option I was considering but I'm surprised that there aren't others looking for this.

**Comment by chrisn** [comment]
Reopening, to keep this on the to-do list.

**Comment by chrisn** [comment]
This is implemented in v0.15.0, please take a look at the `zoomview.dblclick` and `overview.dblclick` events in the documentation.

**Comment by mikearmstrong1** [comment]
Just saw these changes @chrisn  will take a look tomorrow. Excited about that. I think this will allow me to remove side buttons and create a more intuitive user experience.
