### ISSUE TITLE
Make setZoomLevels() public API in Typescript

### ISSUE THREAD

**Issue by tscz** [bbc/peaks.js#295]
Hello @chrisn,

It would be great if the peaks.zoom.setZoomLevels() API would be accessible in Typescript:
https://github.com/bbc/peaks.js/blob/9949309f68f805cad966a4a67a99941c34500b85/src/main/views/waveform.zoomcontroller.js#L28

Explaination of my use case:
* I am currently trying to use the Peaks.js Waveform for song transcriptions. Thus I am interested in dividing the song into measures. "Please show me only segment Verse1 (Measure 16 - 24)" or "show and repeat only measure 14" are my major concerns. This can be achieved basically as recommended in 
https://github.com/bbc/peaks.js/issues/225#issuecomment-390507971 by adjusting the zoomlevels. However I need to update the zoomlevels during runtime, i.e. if I change the time signature (4/4 to 3/4), bpm, start of measure 1, audiosamplerate or the zoomview width. 

Is the setZoomlevel() function meant to be internal only? Are there any issues making it available?

Thanks and regards
Teje

**Comment by chrisn** [comment]
`setZoomLevels` is really an internal method, so it's not as simple as just making it public. The main issue is that once the initial waveform data has been computed, we can't set a lower zoom level, so we'd need to add some parameter validation to prevent this.

For your use case, do you want something more like `setZoomLevel(duration, widthInPixels)`, possibly also with a method to scroll to the right starting point: `setStartPosition(timeInSeconds)`?

**Comment by tscz** [comment]
Ah, good point, that makes `setZoomLevels ` really internal. Your suggestion is great API, the combination of `setZoomLevel(duration, widthInPixels)` and `setStartPosition(timeInSeconds)` would solve my use case. What I really like from your idea is that the API is based on seconds, which is better understandable than samples per pixel:-)

**Comment by chrisn** [comment]
This is resolved in #305.

**Comment by tscz** [comment]
Hi @chrisn,

great, thanks a lot! The new setZoom() and setStartTime methods solve exactly my intended use case here. 

Some comments:
* The new function setStartTime was missing in the doc. But it is intended to be puplic API, right?
* Some type definitions were missing, see pull request https://github.com/bbc/peaks.js/pull/306. It was not straight forward to add the exclusive disjunction for second and scale parameter. Surprisingly, typescript does not support exclusive or out-of-the-box, see https://github.com/Microsoft/TypeScript/issues/14094.

**Comment by chrisn** [comment]
Thanks! I've published a new release v0.18.1 with your changes. I need to do better at keeping the TypeScript declarations in sync...
