### ISSUE TITLE
No segment marker handles, don't respond in demo?

### ISSUE THREAD

**Issue by minirobotdan** [bbc/peaks.js#298]
I can't seem to get any segment markers working in v0.16. I've tried building and running the demo, the handles appear, but aren't interactable, i.e. they can't be dragged. The same thing seems to happen on the [waveform demo](https://waveform.prototyping.bbc.co.uk/). When I add a segment with "editable: true" in my own code, the handles don't appear at all. My use case is (for now) incredibly basic-

```typescript
public addSegments(segments: Peaks.SegmentAddOptions | Peaks.SegmentAddOptions[]): void {
   return this.peaksInstance.segments.add({ startTime: 1, endTime: 2, editable: true });
}
```
My own build:
<img width="917" alt="Screenshot 2019-12-17 at 10 49 21" src="https://user-images.githubusercontent.com/1784933/70989361-65603b00-20bb-11ea-922d-1798f009cb3c.png">

Demo build:
<img width="304" alt="Screenshot 2019-12-17 at 10 49 37" src="https://user-images.githubusercontent.com/1784933/70989350-61ccb400-20bb-11ea-8387-ff9a13bb2bb7.png">

Am I missing something obvious or is there an issue with this build?

**Comment by chrisn** [comment]
I'm not seeing this issue, it works fine for me. Note that the demo page isn't up to date with the latest release (I should do that, really...)

**Comment by minirobotdan** [comment]
Is editable: true all the configuration that should be required to make the handles visible? How are they rendered, to the canvas, or as DOM elements?

**Comment by minirobotdan** [comment]
Never mind- my canvas fingerprinting extension was causing problems!

**Comment by minirobotdan** [comment]
So that resolved the problem with the demo- i still have this problem in my own project. I've created a Stackblitz which reproduces the issue.

https://stackblitz.com/edit/angular-cvzh5h

**Comment by chrisn** [comment]
Are you using an overview or a zoomview waveform? Only the zoomview shows segment handles and allows drag/drop segment editing.

**Comment by minirobotdan** [comment]
Ah, that's most likely it. I overlooked that detail. Can any view be a zoomview? Our clips tend to be short segments of no longer than ~30s.

**Comment by chrisn** [comment]
It depends on the behaviour you want, currently the options we have are: 

* `overview` - total duration fit to a fixed container width, no segment editing
* `zoomview` - scrollable waveform at pre-determined zoom levels, optional segment editing

You can have either or both of these, using the `containers` option.

I'm currently working on a new zoom API that combines both of these, so you can tell the zoomview to zoom to fit the total duration.

**Comment by minirobotdan** [comment]
I see, thanks for the explanation, I'll give it a try. That solves my original issue, I may be back with questions :)
