### ISSUE TITLE
Feature Request: IPython Widget for Jupyter Notebooks

### ISSUE THREAD

**Issue by scottire** [bbc/peaks.js#301]
Hi,

Is there any plans on developing an [IPython Widget ](https://ipywidgets.readthedocs.io/en/latest/index.html) for displaying and interacting with audio within Jupyter Notebooks? 

I'm working through [these tutorials](https://github.com/jupyter-widgets/tutorial) and will be able to help with the development of this.

**Comment by chrisn** [comment]
I don't have any plans, but I'll be interested to take a look if you make something.

**Comment by scottire** [comment]
Cool. I'll close this issue for now.
