### ISSUE TITLE
Time changes by milliseconds when handles are dragged

### ISSUE THREAD

**Issue by Dananji** [bbc/peaks.js#302]
When editing a segment using handles on either side, the time at the other end changes unexpectedly when the handle on one side is dragged.
Steps to reproduce;
There is a segment with the startTime = 90 and endTime = 120
1. Zoom in the waveform to the maximum value possible
2. Drag the handle at the end to change the endTime
3. Log the segment
4. Observe that the startTime has changed by milliseconds
5. Zoom out once
6. Drag the handle for endTime again
7. Log the segment
8. Observe the startTime is changed by milliseconds from the previous time
9. Keep zooming out and dragging the handle at the end, and observe the startTime changing by milliseconds without touching the handle at the start of the segment

![ezgif com-video-to-gif (10)](https://user-images.githubusercontent.com/1331659/72559922-ebff6800-3873-11ea-820e-f51873f70a10.gif)

The .gif is not very clear, but you can see the startTime changes in the bottom where it is logged, after the handle for the endTime is dragged and it changes slightly when the zoom level is changed.

**Comment by chrisn** [comment]
Thank you for reporting this, and providing such clear detail. There is indeed a bug in the segment dragging code that causes the time to change unexpectedly.

**Comment by chrisn** [comment]
@Dananji I have just published a new release to npm, v0.17.0, that fixes this bug. Thanks again.
