### ISSUE TITLE
Different heights for each container

### ISSUE THREAD

**Issue by bestasholli** [bbc/peaks.js#304]
Is it possible to have two different height configuration keys for each container, one for zoomview, and another one for overview?
<img width="1255" alt="Screenshot 2020-01-25 at 2 07 12 PM" src="https://user-images.githubusercontent.com/49398841/73121622-3ff90380-3f7c-11ea-909c-6c62a79a97da.png">

**Comment by chrisn** [comment]
If you use the `containers` config option, Peaks.js will set the heights automatically to fit the container `<div>`s you set for the zoomview and the overview.  As an example, see the demo page [here](https://github.com/bbc/peaks.js/blob/master/demo/index.html#L326) and [here](https://github.com/bbc/peaks.js/blob/master/demo/index.html#L25).
