### ISSUE TITLE
Vertical ZoomView

### ISSUE THREAD

**Issue by abinav-07** [bbc/peaks.js#307]
I want to make the Zoomview Vertical without messing up its mouseDown and other events. Can someone give me suggestions on how to do it?

**Comment by chrisn** [comment]
Implementing this would involve extensive changes to the code, as everything is based around horizontal orientation. You would need to review almost every module and modify the coordinate calculation and rendering.

**Comment by abinav-07** [comment]
oh no! 
Well, Thank You for your response.

**Comment by chrisn** [comment]
Sorry! I'll close this issue, as this isn't a planned feature, bu feel free to ask specific questions if you try to implement it.

**Comment by chrisn** [comment]
Just an idea: perhaps you could try applying a rotation to the `Konva.Stage` or `Kova.Layer` objects?
