### ISSUE TITLE
points events not firing

### ISSUE THREAD

**Issue by sadra-ab** [bbc/peaks.js#311]
Hi all,
I have problem getting callbacks for Point related events.
I can successfully init my instance, and the wave renders correctly. I am also able to add points at desired times on the wave form. 
However, none of the point-related events are getting fired for any of the points. Here's my code:

```
let instance = Peaks.init(options);
instance.on("points.mouseenter", (point) => {
    console.log("points.mouseenter", "point", point);
});
instance.points.add({
    time,
    color: "#FF2B6E",
});
```

![Peaksjs](https://user-images.githubusercontent.com/1020642/73808087-aa8c1980-479c-11ea-9871-efd781b3fefc.png)

I would appreciate any help with this.

**Comment by chrisn** [comment]
I wasn't able to reproduce this problem using the demo/index.html page. Your code looks OK to me, although I would recommend passing a callback to `Peaks.init()`. Which version of Peaks.js are you using?

**Comment by sadra-ab** [comment]
I was using an older version.
After upgrading to "0.19.0", the issue is resolved.

Thanks.
