### ISSUE TITLE
possibility for a dist directory

### ISSUE THREAD

**Issue by jamesb93** [bbc/peaks.js#312]
Would it be possible for the next release to have a dist directory present in the source containing the minified and un-minified js? Most distributions use this so something like `bower` has a uniform place for packed js to be pointed to by the project.

**Comment by chrisn** [comment]
I'll look into this, although I will probably drop Bower support soon (the Bower documentation [recommends moving to Webpack or Parcel](https://bower.io/docs/creating-packages/) for new projects)

**Comment by chrisn** [comment]
This is now implemented
