### ISSUE TITLE
Enable two finger scroll on waveforms? 

### ISSUE THREAD

**Issue by jcheong0428** [bbc/peaks.js#317]
Hi - Is there a way to enable two finger scrolling when navigating the waveforms? 
Using a touchpad, two finger scrolling can be an easier way to navigate the waveform than constantly clicking and dragging. 
I'm curious if this would be a quick addition or a significant undertaking. 
I'd be happy to work on it and submit a PR if successful but any hints or tips on how to get started would be helpful. Thank you.

**Comment by chrisn** [comment]
On my laptop, two-finger scroll affects the whole page, so would it be strange to apply this gesture to the waveform views?

The relevant code is in `MouseDragHandler` [here](https://github.com/bbc/peaks.js/blob/f757fdcfb8fb0d30afb48ca7e40a74fd06f6a251/src/mouse-drag-handler.js) and in the two waveform views [here](https://github.com/bbc/peaks.js/blob/f757fdcfb8fb0d30afb48ca7e40a74fd06f6a251/src/waveform-overview.js#L120) and [here](https://github.com/bbc/peaks.js/blob/f757fdcfb8fb0d30afb48ca7e40a74fd06f6a251/src/waveform-zoomview.js#L125).

**Comment by chrisn** [comment]
This is now implemented, see [`view.setWheelMode()`](https://github.com/bbc/peaks.js#viewsetwheelmodemode).
