### ISSUE TITLE
Event for 'overview.click' and 'zoomview.click'

### ISSUE THREAD

**Issue by elastisteve** [bbc/peaks.js#318]
I need to know if the user clicks in the overview or zoomview. In the docs, I only found a way to capture double-clicks ('overview.dblclick') and not "regular" ones.

Is there a way at the moment?

thanks

great product BTW!

**Comment by elasticsteve** [comment]
Just found that there is "player_seek" browsing through issues...

Would be great if this could be added to docs.

Are there any other undocumented events?

cheers

**Comment by chrisn** [comment]
Single clicks are already handled internally, for scrolling (zoomview), changing playback position (overview), or adjusting marker positions. How does your application want to handle these events?

**Comment by chrisn** [comment]
There are numerous undocumented events. Applications should stick to the documented API, as anything else can (and does) change between versions. That said, I'm happy to consider making certain events part of the public API where there's a need.

**Comment by elasticsteve** [comment]
I have a key (numpadEnter - Wavelab is using the same) to repeat the last start position (play again).

I capture the time when the user hits play, but I also need to update this when the user clicks at the waveform.

"player_seek" works perfect.

**Comment by chrisn** [comment]
Sounds good. If we make the player events public, I'll rename them for consistency: (a) with other Peaks.js events, which use period not underscore, and (b) with the [HTMLMediaElement events](https://html.spec.whatwg.org/multipage/media.html#mediaevents) - so `player_seek` would become `player.seeked`.

If we implement this, is there also a need for the click events?

**Comment by elastisteve** [comment]
Many thanks. Click events?

**Comment by chrisn** [comment]
Yes, from your original issue:
> I need to know if the user clicks in the overview or zoomview.

**Comment by elastisteve** [comment]
I'm confused. What is the difference to player_seek? :)

**Comment by chrisn** [comment]
I'm also confused. I'm trying to understand if `player_seek` by itself solves your use case, or if you need specific click events in addition to that.

**Comment by elastisteve** [comment]
I think I know what the difference is. I guess it would be good to have a click event too, as this is actually more suitable to what I wanted to do.

IMO player.seeked and overview.click and zoomview.click would be perfect.

**Comment by elastisteve** [comment]
For my application overview.click and zoomview.click would be sufficient. (reporting back the time)

**Comment by chrisn** [comment]
I see, the difference is that `player_seek` happens after a seek, which may or not have been caused by a user click (e.g, the web app may call `player.seek()`). There's also the situation where a click may not result in a successful seek (e.g., network issue fetching the audio/video media).

**Comment by elastisteve** [comment]
Exactly. In my case I get double triggers, which don't do any damage when using player.seek, but the click event would be more elegant.

**Comment by chrisn** [comment]
`zoomview.click` and `overview.click` events have been added in https://github.com/bbc/peaks.js/commit/4d97e540c303433fb4e64b8afe82c88fb7331354.
