### ISSUE TITLE
Amplitude / Phase incorrect

### ISSUE THREAD

**Issue by elastisteve** [bbc/peaks.js#321]
I used a 40 Hz sine wave to do a few tests and noticed that the amplitude is incorrect.

It was recorded so it starts with a positive amplitude, which is also what Steinberg Wavelab shows in the attached picture. In the other picture you see peaks.js (Chrome Win 10) starting on the negative (down side).

Any idea? Positive values should be up, right?

thanks

Steinberg Wavelab:
![image](https://user-images.githubusercontent.com/10718044/85340077-57adc700-b4dd-11ea-9877-e79d15afc76f.png)

Peaks.js:
![image](https://user-images.githubusercontent.com/10718044/85340096-5d0b1180-b4dd-11ea-83c5-0849c97bcb37.png)

The 40 Hz wav file I used can be downloaded from here:
[https://www.dropbox.com/s/kbg1haoojvmn473/0%20-%20sine%2040Hz_norm.wav?dl=0](https://www.dropbox.com/s/kbg1haoojvmn473/0%20-%20sine%2040Hz_norm.wav?dl=0)

**Comment by chrisn** [comment]
Yes, you're quite right! We'll work on a fix.

**Comment by elastisteve** [comment]
Thanks! Looking forward to it!

**Comment by elastisteve** [comment]
Hi Chris

Any news on this? Would be great to see the waveforms in the right orientation! :)

**Comment by chrisn** [comment]
I have a fix under way. Sorry for the slow progress.

**Comment by elastisteve** [comment]
Excellent! Thanks!

**Comment by chrisn** [comment]
Please try out the [`fix-waveform-inversion`](https://github.com/bbc/peaks.js/tree/fix-waveform-inversion) branch. If this works for you, I'll prepare a new release with this fix.

**Comment by elastisteve** [comment]
Thanks Chris and apologies for my silly question: do I have to build the peaks,js file? I see that I have one in my local folder, but no recollection how I got that. All I know is that I modded it to have custom fonts (which was another request I had) so it's easiest at that point to replace my local peaks.js with another version until you also integrated the option for font-family, then I can go back to npm.

**Comment by chrisn** [comment]
Yes, you can clone this repo, check out the branch, then do `npm install` then `npm run build` to create the peaks.js file.

I'll try to look at the font change soon. You're welcome to send a pull request if you want to.

**Comment by elastisteve** [comment]
I stopped coding a year ago and wouldn't be up to the job of a pull request ;) We have an inhouse dev team now. I built the prototype of the platform that uses peaks.js, which my devs inherited, but they are furloughed so I try to sort this.

Will report back tomorrow... Appreciate your effort!

**Comment by elastisteve** [comment]
Chris, sorry for the delay. I now had a chance to test it. Works great! Thank you!

**Comment by chrisn** [comment]
Thank you! I have just merged this branch.
