### ISSUE TITLE
Points click event

### ISSUE THREAD

**Issue by uniquexor** [bbc/peaks.js#324]
Am I missing something or is there no click event for points? I can see one for segments, but can't find a way to handle click event for points. If there is none, it would be great to have one.

**Comment by chrisn** [comment]
The API is inconsistent, so we should fix that. We have double-click events for the waveform views, click events for segments and double-click events for points. It would seem that we should support both click and double-click events for everything.

Related issue: https://github.com/bbc/peaks.js/issues/318

**Comment by rowild** [comment]
Trying to find out what `dblClick` on a Point should do.

Currently I can click on the rectangle of a point (-line) and then drag it left and right. It does so with one click.

But I assume there is (or should be) different behaviour associated with it?

**Comment by chrisn** [comment]
Double-clicking a point marker (the rectangle handle) will generate a `points.dblclick` event.

**Comment by rowild** [comment]
...and I am free to define what the dblClick event does?

**Comment by chrisn** [comment]
Yes, the intent of these events is to allow your application to do whatever it wants, by adding an event handler. There's an example [here](https://github.com/bbc/peaks.js/blob/2c81ae5f20b0026d7be1b4cf022a29310f12c9b3/demo/index.html#L525).

**Comment by rowild** [comment]
Aaaah!!! The clouds thin out! – It seems Point and Segment have very different implementations of those events. But If I am not completely mistaken: Point.click could be implemented "simply" by following the traces of dblClick. If that is so, I could try to add it and provide a PR. 
But at some other place you mention you have a local ES6-Module based version. May it is already implemented there; or it won't make much sense to implement the click behaviour in this version?

**Comment by chrisn** [comment]
Thanks. I'll implement this, it's no problem to rebase the ES module change.
