### ISSUE TITLE
feature request: font family in options

### ISSUE THREAD

**Issue by elastisteve** [bbc/peaks.js#325]
Hi

Great product!

Would be nice if we could use other fonts than the default Arial.

Just to be able to add your own font-family name to the options would be great.

At the moment I have to 'hack' peaks.js which makes updates a pain... :(

My coding skill aren't good enough to go for a pull request,,,

**Comment by chrisn** [comment]
Thanks for the kind words!

Is it just the font-family that you need, or do you also need to be able to set the font size? Would this be a single global setting or separate settings for the time axis labels, playhead time label, point/segment markers?

**Comment by elastisteve** [comment]
Thanks for your quick response!

For me a global font-family setting without size would be sufficient for the moment.
