### ISSUE TITLE
Quasar/Vue + Safari doesn't render webAudio + other Safari issues

### ISSUE THREAD

**Issue by sonicviz** [bbc/peaks.js#330]
I have a strange issue on iOS that I can't figure out.
I'm using the Demo: Changing the Media URL as a test integration into Quasar/Vue.

It works fine on Windows/Android, but (as usual) iOS Safari has "issues" due to its webkit implementation. 

If you just run the Demo: Changing the Media URL on iOS Safari without changes you will immediately notice one issue that I think is possibly the root cause of the Quasar/Vue issue I have. 
When you change the URL to the webaudio file the waveform view doesn't get refreshed automatically like windows/android.  You need to press play first before the waveform for the loaded file will show.

My Quasar/Vue implementation of  Demo: Changing the Media URL works fine on windows/android. Everything works as expected, clicks, changing url, waveform rerendering. 
In my Quasar/vue implementation on Safari pressing play results in the audio file playing but the waveform does not get refreshed. Also, clicking on the waveform works for the cursor but the segment block does not change so you can't set segments. Zoom works though. 

Quite possibly it's related to:
// Safari 11 or newer automatically suspends new AudioContext's that aren't
// created in response to a user-gesture, like a click or tap, so create one
// here (inc. the script processor)
https://github.com/katspaugh/wavesurfer.js/blob/master/example/microphone/app.js#L12

I've tried creating a new audioContext for the webaudio file load as well, but doesn't work either. 

Any clues on how to resolve this and get it working quasar/vue would be great. 
Integrating Peaks.js into modern frameworks like Quasar/vue would be highly beneficial I think. 
Unfortunately it's Safari that isn't playing nice, so need to track down why.

**Comment by chrisn** [comment]
I don't have access to Safari to test against, but one idea could be to move construction of the `AudioContext` in demo/set-source.html to the select box's `change` handler, e.g.:

```diff
diff --git a/demo/set-source.html b/demo/set-source.html
index 8b8cd13..b59edc2 100644
--- a/demo/set-source.html
+++ b/demo/set-source.html
@@ -141,9 +141,6 @@
     <script src="peaks.js"></script>
     <script>
       (function(Peaks) {
-        var AudioContext = window.AudioContext || window.webkitAudioContext;
-        var audioContext = new AudioContext();
-
         function requestWaveformData(url) {
           return fetch(url)
             .then(function(response) {
@@ -165,7 +162,7 @@
               title: 'Desert Island Discs',
               mediaUrl: 'sample.mp3',
               webAudio: {
-                audioContext: audioContext
+                audioContext: null
               },
               zoomLevels: [128, 256]
             },
@@ -212,6 +209,11 @@
           select.addEventListener('change', function(event) {
             var source = sources[event.target.value];

+            if (source.webAudio && !source.webAudio.audioContext) {
+              var AudioContext = window.AudioContext || window.webkitAudioContext;
+              source.webAudio.audioContext = new AudioContext();
+            }
+
             peaksInstance.setSource(source, function(error) {
               if (error) {
                 console.error('setSource error', error);
```

I don't know anything about Quasar/Vue so I'm sorry I can't advise on that.

**Comment by sonicviz** [comment]
Yeah, I'd already tried that (as mentioned in "I've tried creating a new audioContext for the webaudio file load as well, but doesn't work either.") but no joy. 

Apple is really painfully annoying the way iOS/Webkit just won't do what other browsers do.

**Comment by sonicviz** [comment]
Unfortunately still can't get iOS Safari to:
. Work with waveform touch/clicks ie: doesn't change the cursor position
. Update the waveform properly when a new file is loaded by whatever method

Possibly the waveform click issue is related to the waveform not displaying properly. Works fine on desktop/android chrome.

**Comment by sonicviz** [comment]
Update: Got it working on Safari with a couple of provisos.

. I can load a file but the waveform won't show until I press play.
. Only seems to process the main audiocontext so can't use sountouch, which works fine on PC/Android.

I'll close this now. Thanks for the help and the cool tool!
