### ISSUE TITLE
Issues with Uploading a file to webaudio 

### ISSUE THREAD

**Issue by sonicviz** [bbc/peaks.js#331]
I'm using the guidance here https://github.com/bbc/peaks.js#web-audio-based-waveforms to load in a file via the webaudio method that's been uploaded via a standard javascript input field method.

"Alternatively, if you have an AudioBuffer containing decoded audio samples, e.g., from AudioContext.decodeAudioData then an AudioContext is not needed"
+
"audioBuffer: (optional) A Web Audio AudioBuffer instance, containing the decoded audio samples. If present, this audio data is used and the mediaUrl is not fetched."

My loadfile method (vue) is copied below for reference.
It loads the file ok, and the arrayBuffer is correctly converted to an audioBuffer for setting in the peak source options.
However, it returns an error trying to set the source on peaks.

**1dab80e7-54ab-4600-9d0c-a23bc6921156:44 Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.setInt32 (<anonymous>)
    at 1dab80e7-54ab-4600-9d0c-a23bc6921156:44**

The sample audio files I'm using to test upload from local file system are the mp3 files from https://file-examples.com/index.php/sample-audio-files/sample-mp3-download/

Also, if I put anything in mediaUrl that doesn't resolve to an actual local file it also returns a 404, though it's supposed to ignore the mediaURL if audioBuffer exists (according to the docs link above). It also seems to be loading this mediaURL, despite saying it will ignore it if audioBuffer is being used (I'm reusing the sample file from your demo)

Any clues?

My Vue.js loadfile method:

    loadFile(file) {
      if (file.target.files.length == 0) return;
      //Convert the loaded file to an arraybuffer
      var url = URL.createObjectURL( file.target.files[0]);
      var source = {
        title: "Uploaded file",
        mediaUrl: "audio/sample.mp3",
        webAudio: {
          audioBuffer: null,
          scale: 128,
          multiChannel: false
        },
        zoomLevels: [128, 256, 512, 1024, 2048, 4096]
      }
      fetch(url).then(function(response) {
        if(response.ok) {
            response.arrayBuffer().then(function(buffer) {
            // do something with buffer
            console.log(buffer)
            var AudioContext = window.AudioContext || window.webkitAudioContext;
            var context = new AudioContext();
            var newAudioBuffer = context.decodeAudioData(buffer);
            console.log("Here's the audioBuffer");
            console.log(newAudioBuffer)
            source.webAudio.audioBuffer = newAudioBuffer
            console.log(source)
          });
          return true;
        }
        throw new Error('Network response was not ok.');
      })
      this.peaksInstance.setSource(source, function(error) {
        if (error) {
          console.error("setSource error", error);
        }
      });

    },

**Comment by sonicviz** [comment]
Q: Is it possible to load a file as above but use the audiocontext method?

**Comment by chrisn** [comment]
The following code works for me:
```js
const upload = document.getElementById('upload'); // <input> element

upload.addEventListener('change', function(event) {
  const file = event.target.files[0];
  const url = URL.createObjectURL(file);

  const AudioContext = window.AudioContext || window.webkitAudioContext;
  const audioContext = new AudioContext();

  peaksInstance.setSource({
    mediaUrl: url,
    webAudio: {
      audioContext: audioContext
    }
  });
});
```

The `mediaUrl` option in `setSource()` isn't ignored as it's a required parameter. All others are documented as optional.

**Comment by sonicviz** [comment]
Doh! I should have tried the URL myself first as I has it already, before bothering you! 
Works fine, thanks for the quick feedback. 

I'd suggest adding that to the demo/examples as it's a common use case I think. 

>>The mediaUrl option in setSource() isn't ignored as it's a required parameter. All others are documented as optional.

Required even when it's not used in the audioBuffer case? ie: "audioBuffer: (optional) A Web Audio AudioBuffer instance, containing the decoded audio samples. If present, this audio data is used and the mediaUrl is not fetched."
