### ISSUE TITLE
Question : Is it possible to have multiple files & waveforms in a single bar

### ISSUE THREAD

**Issue by TheFrankman** [bbc/peaks.js#333]
Hello There,

Is it possible to initialise peaks with multiple audio-files and waveforms in a single instance ?

We'd essentially like to preview what a the output of various stitched together files would be.

I am unable to see anything documented or any related queries.

**Comment by chrisn** [comment]
That's not currently possible, as all the views are based on the same (single) waveform and media player.

**Comment by TheFrankman** [comment]
> That's not currently possible, as all the views are based on the same (single) waveform and media player.

Thanks @chrisn
