### ISSUE TITLE
Implementing peaks.js in a React component

### ISSUE THREAD

**Issue by jamesb93** [bbc/peaks.js#334]
Hi there,

I am trying to bash my way through creating a React component which will host a single waveform viewer instance. I've scoured the previous issues to see if anyone has a solid example around before I asked but I am getting quite stuck trying to implement - especially with how the Peaks.init factory relates to the DOM nodes.

Would you be able to point me in the right direction for getting a React component to render properly? So far I have this:

```jsx
import React from 'react';
import Peaks from 'peaks.js';

    
export class Waveform extends React.Component {
    constructor(props) {
        super(props);
        this.overviewRef = React.createRef();
        this.zoomRef = React.createRef();
        this.audioRef = React.createRef();
    }

    get pathToAudio() {
        return process.env.PUBLIC_URL + '/audio/' + this.props.audioPath
    }

    componentDidMount() {
        const overview = this.overviewRef.current;
        console.log(this.audioRef)

        const zoom = this.zoomRef.current;
        const audio = this.audioRef.current;
        this.peaksInstance = Peaks.init({
            containers: {
                zoomview: zoom,
                overview: overview
            },
            mediaElement: audio,
            height: 60,
            segmentStartMarkerColor: '#a0a0a0',
            segmentEndMarkerColor: '#a0a0a0',
            zoomWaveformColor: 'rgba(0, 30, 128, 0.61)',
            overviewWaveformColor: 'rgba(0, 15, 100, 0.3)',
            overviewHighlightColor: 'grey',
            segmentColor: 'rgba(255, 161, 39, 1)',
            playheadColor: 'rgba(0, 0, 0, 1)',
            playheadTextColor: '#aaa',
            showPlayheadTime: false,
            pointMarkerColor: '#FF0000',
            axisGridlineColor: '#ccc',
            axisLabelColor: '#aaa',
            randomizeSegmentColor: true
        })
    }


    render () {
        return (
            <div>
                <div ref={this.overviewRef} />
                <div ref={this.zoomRef} />
                <div id="peaks-control">
                    <audio ref={this.audioRef}>
                        <source src={this.pathToAudio} type="audio/wav"></source>
                    </audio>
                </div>
            </div>
        )
    }
}

export default Waveform;
  ```
which compiles fine but renders to a blank screen. I believe its possibly my naive use of refs, but I can't see a way around using them because I need to create a peaks instance that points to the divs when the component is mounted.

Thanks for all your hardwork.

James

**Comment by chrisn** [comment]
At first glance, this looks good to me. I made a similar React component using the same approach, which works fine.

**Comment by jamesb93** [comment]
Okay, I'll investigate further why it doesn't seem to play very nicely. I do get the right div structure where the app is rendered to, but its blank. They don't have id's because I'm using ref so perhaps this has a part to play. Anyway - I'll plug along and let you know if I do across some other complexity.

**Comment by chrisn** [comment]
I have published a React example, which I hope is useful to you: https://github.com/chrisn/peaksjs-react-example

**Comment by jamesb93** [comment]
This is immensely useful for both learning and using it in my own stuff. Cheers Chris.
