### ISSUE TITLE
Additional attributes to the Segment object

### ISSUE THREAD

**Issue by msjaber** [bbc/peaks.js#336]
Hey,

Is it possible to add additional attributes to the Segment object?

```javascript
{
    startTime: 1,
    endTime: 3,
    editable: true,
    color: "#ff0000",
    labelText: "My label",
    foo: "bar",  // additional attributes
}
```

If no, can I make a pull request for it?

My use case is that I wanna add an attribute of `shouldSkip`, and listen to the cue events in order to behave based on the attribute's value.

Thanks

**Comment by chrisn** [comment]
This is currently not possible, but I think it should be. I'll have a look into it, as implementing this will require some changes to the way the point/segment attributes are handled.

**Comment by chrisn** [comment]
Please take a look at the [`segment-attributes`](https://github.com/bbc/peaks.js/tree/segment-attributes) branch. You can now set custom attributes using `peaks.segments.add()` and `segment.update()`:

```js
peaks.segments.add({
  startTime: 1,
  endTime: 3,
  editable: true,
  color: "#ff0000",
  labelText: "My label",
  foo: "bar"  // additional attributes
});

segment.update({ foo: "baz" });
```

**Comment by msjaber** [comment]
Thank you so much @chrisn! 🙏🏻

It works perfectly.

**Comment by chrisn** [comment]
Thank you :-)  I'll merge this and publish a new release to npm.
