### ISSUE TITLE
Demo app in Angular?

### ISSUE THREAD

**Issue by itaishalom** [bbc/peaks.js#337]
Is it possible to see some examples written in type script?
Trying to use the library in an Angular 10 project.
Thanks.

**Comment by dacarter** [comment]
@itaishalom Just wondering if you ever figured this out? I'm trying to migrate peaks from AngularJS to Angular 13 and having all kinds of problems.

**Comment by itaishalom** [comment]
@dacarter I'm not working on the project anymore.
Good luck.

**Comment by chrisn** [comment]
I have made a demo: https://github.com/chrisn/peaksjs-angular-example
