### ISSUE TITLE
Peak js-not able to add and update custom attributes to segments

### ISSUE THREAD

**Issue by jaijos** [bbc/peaks.js#339]
Hello

I have tried

peaksInstance.segments.add({
          startTime: lastPonint,
          endTime: peaksInstance.player.getCurrentTime(),
          labelText: "",
          editable: false,
          speakerId: "",
        })

and

currentSegment.update(speakerId:"SpeakerId1");

But both the codes are not working.

All the predefined attributes are getting added, but not the user-defined or the custom attributes.

Please Help. It's an urgent requirement and I am stuck here.

Thanks in advance.

**Comment by chrisn** [comment]
This works fine for me in Peaks.js 0.22.0. Please check that you are using the latest version.

**Comment by jaijos** [comment]
Thank you Chris, I will try after updating my package with the latest
version.

**Comment by jaijos** [comment]
Hi  Chris,

I have tried to install 0.22.0
npm install --save peaks.js@0.22.0

But I am getting  an error
No matching version found for peaks.js@0.22.0.

Even when I did google search for latest  version of peaks.js, it is
showing 0.21.0, which is already installed in my app.

**Comment by chrisn** [comment]
OK, it seems 0.22.0 hasn't been published to NPM yet. I'll reply here when that is done.

**Comment by jaijos** [comment]
Okay, sure. Thank you.

**Comment by chrisn** [comment]
Peaks.js 0.22.0 is now available via NPM. Sorry for the inconvenience.

**Comment by jaijos** [comment]
Issue is resolved. Installed 0.22.0 version. I am able to add and update
custom attribute to a segment now. Thank you.
