### ISSUE TITLE
disable time stamps / customize timestamps

### ISSUE THREAD

**Issue by Nadav42** [bbc/peaks.js#340]
Hey, can you add a way to disable or customize timestamps?

![image](https://user-images.githubusercontent.com/48027340/97084643-2414b200-1621-11eb-915a-6fbe974e6f07.png)

a way to pass custom timestamps generator which is a function that takes the time and returns a string will be nice, something like how you can pass an option for custom player adapter:

usage to generate custom string format:
```
timestampsGenerator(time: number) {
   return "1m 2s"; // moment(...).format(...);
}
```

usage to disable time stamps:
```
timestampsGenerator(time: number) {
   return null; // or empty string?
}
```

then set ```timestampsGenerator: ...``` option in the config

**Comment by chrisn** [comment]
Thank you for the suggestion!

If we implement this, we may want to add an option to also remove the vertical lines next to the timestamps.

We could also consider whether to allow customization of the timestamp shown next to the playhead (and how this interacts with the `timeLabelPrecision` config option).

**Comment by Frederick-88** [comment]
Hello, can know if there is any update about this disabling timestamp feature

**Comment by chrisn** [comment]
Hi Frederick, there's no progress on this so far (I'm currently working on updating the code to ES modules). 

The options we currently have are:

* `showPlayheadTime` (boolean) - shows or hides the timestamp next to the playhead
* `timeLabelPrecision` (number) - sets the number of decimal places for the timestamp next to the playhead

I think the options we can add are:

* `formatAxisTime` (function) - formats the axis label timestamps
* `showAxisTimeLabels` (boolean) - show or hides the axis label timestamps
* `formatPlayheadTime` (function) - formats the playhead marker timestamp (if used, `timeLabelPrecision` is ignored)

**Comment by chrisn** [comment]
This is now implemented and will be included in the next release.
