### ISSUE TITLE
React wrapper for peaks.js?

### ISSUE THREAD

**Issue by larrywal** [bbc/peaks.js#342]
Has anyone created something for this?  Right now I'm using refs to interact with Peaks.js in my react app, but would love to have a react control.

**Comment by chrisn** [comment]
There's a demo of how to use Peaks.js in React here: https://github.com/chrisn/peaksjs-react-example

**Comment by larrywal** [comment]
Thanks!  So helpful.  From looking through, I think for just a basic waveform rendering, I can take waveform.jsx and use it directly...

I do need to use seek and zoom, but if I pass those in to waveform as properties, and then in componentDidUpdate, if the file hasn't changed but the zoom/seek have, I could just call those functions directly on the element.

Sound right?

**Comment by rowild** [comment]
@chrisn Any chance for a Vue example?

**Comment by suterma** [comment]
@rowild Giovanni Candeo has a working vue.js example: https://github.com/candeogi/peaks-vue-demo 
It's very bare-bones but shows some basic options.
