### ISSUE TITLE
Question: play audio while moving segment end marker

### ISSUE THREAD

**Issue by TaridaGeorge** [bbc/peaks.js#346]
Is it possible that while moving the segment end marker to be able to also play the audio file at that marker updated position?

Are there any callbacks for when a segment mark is moved?

**Comment by chrisn** [comment]
Peaks.js emits events when segment markers are moved. The [event documentation](https://github.com/bbc/peaks.js#events) has more information: `segments.dragstart`, `segments.dragged`, and `segments.dragend`.

**Comment by TaridaGeorge** [comment]
Thank you!
