### ISSUE TITLE
Match wave amplitude in segments 

### ISSUE THREAD

**Issue by JonathanDillon** [bbc/peaks.js#348]
I've had to lower the amplitude scale on my wave form to fit in in the canvas. Using this:
getView('zoomview').setAmplitudeScale(0.003)

However when I set a segment on this file it gets displayed at the original Amplitude rather than the new one. So the segment wave is at a completely different size to the full file wave. 

I can't see a fix for this in the segment API documentation. Is it possible to do, am I doing something wrong?

<img width="464" alt="Peaks Segment wave example" src="https://user-images.githubusercontent.com/6214134/102643196-cef3a900-4156-11eb-8e5d-5f6f100a7e04.png">

**Comment by chrisn** [comment]
Thanks for reporting this. What version of Peaks.js are you using? There was a bug like this in an older version. Also, what number range do you have in your waveform data? Peaks.js expects values in the range -128 to 127.

**Comment by JonathanDillon** [comment]
Hi Chris, thanks for the quick reply. Looks like we're using the audiowaveform default of 16 bits rather than setting to 8. Should be an easy fix. Thanks.
