### ISSUE TITLE
Zoomed waveform does not autoscroll

### ISSUE THREAD

**Issue by Christilut** [bbc/peaks.js#349]
I have both waveforms set up and the overview waveform works as expected. The zoomed waveform also shows the current position with the marker but it does not autoscroll with the current position of the playing music. After the first few seconds, the marker just goes offscreen and the zoomed waveform does not move.

I'm using Howler as my external player.

Here is my code:
```ts
async load(location: string) {
    const arrayBuffer = new Uint8Array(await readFile(location)).buffer

    const dataUri = 'data:' + 'audio/mp3' + ';base64,' + base64ArrayBuffer(arrayBuffer)

    const audioContext: AudioContext = new AudioContext()

    const audioBuffer: AudioBuffer = await audioContext.decodeAudioData(arrayBuffer)

    this.peaks = await Peaks.init({
      containers: {
        overview: this.overviewContainer,
        zoomview: this.container
      },
      mediaElement: undefined as any,
      webAudio: {
        audioContext,
        audioBuffer
      },
      overviewWaveformColor: '#18c518',
      overviewHighlightColor: '#fff',
      zoomWaveformColor: '#18c518',
      segmentStartMarkerColor: '#fff',
      segmentEndMarkerColor: '#fff',
      segmentColor: 'rgba(255, 255, 255, 0.5)',
      playheadColor: '#fff',
      player: {
        init: () => {
          this.howl = new Howl({
            src: [dataUri],
            html5: true
          })
        },

        destroy: () => {
          this.howl.unload()
        },

        play: () => {
          this.howl.play()
        },

        pause: () => {
          this.howl.pause()
        },

        seek: (seconds) => {
          this.howl.seek(seconds)
        },

        isPlaying: () => {
          return this.howl.playing()
        },

        isSeeking: () => {
          return false
        },

        getCurrentTime: () => {
          return this.howl.seek()
        },

        getDuration: () => {
          return this.howl.duration()
        }
      }
    })
}
```

Any ideas?

**Comment by Christilut** [comment]
I tried
```
    const view = this.peaks.views.getView('zoomview')

    view?.enableAutoScroll(true)
```

But this does not change anything

**Comment by chrisn** [comment]
To get the playhead position to update, and for auto-scroll to work, your player implementation should emit `player.timeupdate` events. See https://github.com/bbc/peaks.js/blob/master/customizing.md#events, and the Tone.js example [here](https://github.com/bbc/peaks.js/blob/master/demo/external-player.html#L167).

**Comment by Christilut** [comment]
Perfect, thanks! 
Quick followup question: is it possible to get the position marker in the zoomed waveform to always be in the middle? Now it moves from start to end of the zoom and then renders a new zoom, but I want to it to be in the middle and let the waveform move under it continuously.
Is that possible already or should I make a PR for that? And any hints where I should start would be great :)

**Comment by chrisn** [comment]
That's currently not possible, but I'm open to adding it as a new feature. Feel free to open a new issue and I'll share a few pointers. Thanks!
