### ISSUE TITLE
Division by zero results in infinite loop

### ISSUE THREAD

**Issue by ffxsam** [bbc/peaks.js#365]
I'm referring to this particular part of `waveform-data`:

https://github.com/bbc/waveform-data.js/blob/6267a999bf0e7b772b8e6222fe042b94ebac0826/lib/core.js#L220-L221

If a zero width or scale is passed via the resample method, it results in a value of `Infinity` for the scale, which causes this loop to run indefinitely.

I'd fix this myself, @chrisn, but I'm not sure how you wanted to handle it (throwing an error, etc) or where.

**Comment by ffxsam** [comment]
Or prevent it at these points:

https://github.com/bbc/peaks.js/blob/6eed95322b6303c8a7c8fbff9d3a7c35e37bac0c/src/waveform-overview.js#L215
https://github.com/bbc/peaks.js/blob/6eed95322b6303c8a7c8fbff9d3a7c35e37bac0c/src/waveform-zoomview.js#L226

**Comment by chrisn** [comment]
There are already checks [here](https://github.com/bbc/waveform-data.js/blob/6267a999bf0e7b772b8e6222fe042b94ebac0826/lib/core.js#L156-L162), so you should be getting a `RangeError` if the width is zero.

**Comment by ffxsam** [comment]
Hmm, let me zero in on how this is happening. I'll post again once I have more details.

**Comment by ffxsam** [comment]
I'll close this for now until I'm able to replicate again.
