### ISSUE TITLE
Custom segment markers are not interactable when using build tools (Webpack, Pacel)

### ISSUE THREAD

**Issue by dutzi** [bbc/peaks.js#368]
I'm trying to implement customized segment markers, but it seems that many popular build tools (Webpack, when using Create React App and Parcel) are breaking them, making them non-interact-able.

I've forked @chrisn's [React Example](https://github.com/chrisn/peaksjs-react-example), and made [this](https://github.com/dutzi/peaksjs-react-example/).

I then created a `createSegmentMarker` function that instantiates the `DefaultSegmentMarker` I took straight from Peaks.js' code.

When running [my fork](https://github.com/dutzi/peaksjs-react-example) you can create a segment (by clicking on Create Segment), and it _will_ work, but that segment is not intractable. I.e., you cannot drag its handles to resize it.

**Comment by dutzi** [comment]
It seems like an issue related to how Konva is packaged.

When calling `window.Konva` (instead of importing) everything works.

**Comment by chrisn** [comment]
Thank you for reporting this. I wonder if changing Peaks.js to use Webpack or Parcel would help?

**Comment by dutzi** [comment]
Happy to help. I'll give it a shot, I think Rollup is more oriented towards third party libraries, like Peaks.js.

**Comment by chrisn** [comment]
Related: https://github.com/bbc/peaks.js/issues/310#issuecomment-855465401

**Comment by huanle0610** [comment]
> Thank you for reporting this. I wonder if changing Peaks.js to use Webpack or Parcel would help?

@chrisn 

I found the key point is "rollup-plugin-peer-deps-external" doesn't work well.

After I changed to a new plugin for rollup, Custom segment markers are interactable.

`import excludeDependenciesFromBundle from 'rollup-plugin-exclude-dependencies-from-bundle';`

`excludeDependenciesFromBundle({ peerDependencies: true }),`

BTW, I tried in a CRA(webpack) project.

**Comment by chrisn** [comment]
This is now fixed in v0.27.0, and I've updated the [React example](https://github.com/chrisn/peaksjs-react-example).

You can either use the Peaks.js ES bundle with Webpack or Rollup etc, or there is the peaks.ext.js / peaks.ext.min.js UMD build that does not include Konva.
