### ISSUE TITLE
setSource required MediaElement option when used with external player

### ISSUE THREAD

**Issue by LukaMoria** [bbc/peaks.js#370]
Hey! I used external player when initiallization and all works fine for first track but when I request waveform data from the server and wanna to replace one on another. But looks that I cannot to do that.
```
_changePeaksSource = (waveform, music) => {
    const sourceOptions = {
      mediaUrl: music.hls || music.http,
      waveformData: { json: waveform }
    }

    this._peakInstance.setSource(sourceOptions, (err) => {
      console.log(err)
    })
  }
```
![image](https://user-images.githubusercontent.com/17146241/109519563-67de6300-7abc-11eb-8be0-94962a5b1755.png)

**Comment by chrisn** [comment]
Thanks for reporting this. This bug was fixed in 1a91b659. I will publish a new release version to NPM soon.

**Comment by LukaMoria** [comment]
@chrisn
Cool, really waiting new version, thank you)

**Comment by chrisn** [comment]
Version 0.24.0 is now available via npm.  Please re-open this issue if you still have problems.
