### ISSUE TITLE
PeakJS silently fails to initialize on iOS when created with { audioContext: audioContext } ?

### ISSUE THREAD

**Issue by OmarShehata** [bbc/peaks.js#372]
If I initialize PeakJS as follows, it seems to work correctly everywhere except on iOS devices, and it fails with no console errors or warnings. The visualization just doesn't show up:

```javascript
const audioContext = new AudioContext();
const response = await fetch(soundFileUrl);
const arrayBuffer = await response.arrayBuffer();
const audioBuffer = await audioContext.decodeAudioData(arrayBuffer);
// This works everywhere but not on iOS
peaks.init(
    containers: {
      zoomview: zoomview
    },
    mediaElement: audioElement,
   webAudio : { audioContext: audioContext }
  });
```

Link to a live minimal example: https://peakjs-safari-bug.glitch.me/.
Source code: https://glitch.com/edit/#!/peakjs-safari-bug?path=script.js%3A3%3A58

The fix is to pass the audioBuffer instead of the audioContext:

```javascript
// Works everywhere including iOS
peaks.init(
    containers: {
      zoomview: zoomview
    },
    mediaElement: audioElement,
   webAudio : { audioBuffer: audioBuffer }
  });
```

Minimal example: https://peakjs-safari-bug.glitch.me/?mode=audiocontext. Source code same as above.

My questions are:

1. Is this expected behavior?
2. If it's a bug, any idea what could be going wrong? I wasn't sure where to begin debugging this since it was a silent failure. Happy to dig a bit deeper and open a PR.

**Comment by chrisn** [comment]
This isn't expected behavour - when you pass in an `audioContext`, Peaks.js will request the audio file and call `decodeAudioData` for you. I don't have an iOS device to test with, so I don't know what's happening (although I can probably get access to Browserstack to try it myself). Thank you for offering to help debug this!

The expected call flow when you pass in an `audioContext` will be:

1. [`WaveformBuilder._buildWaveformDataUsingWebAudio`](https://github.com/bbc/peaks.js/blob/5a20b456fd064804aea723841137209554562459/src/waveform-builder.js#L282) - What does `mediaSourceUrl` contain? If it's not set, does the `player.canplay` event fire?
2. [`WaveformBuilder.prototype._requestAudioAndBuildWaveformData`](https://github.com/bbc/peaks.js/blob/5a20b456fd064804aea723841137209554562459/src/waveform-builder.js#L352)
3. [`WaveformData.createFromAudio`](https://github.com/bbc/waveform-data.js/blob/d720259d882ebbc5bbf1a6029820582a415979d2/lib/builders/webaudio.js#L69) - This is in the [waveform-data.js](https://github.com/bbc/waveform-data.js) library. 
4. [`createFromArrayBuffer`](https://github.com/bbc/waveform-data.js/blob/d720259d882ebbc5bbf1a6029820582a415979d2/lib/builders/webaudio.js#L6) - This is where `decodeAudioData` is called.
5. [`onAudioDecoded`](https://github.com/bbc/waveform-data.js/blob/d720259d882ebbc5bbf1a6029820582a415979d2/lib/builders/audiodecoder.js#L166)
6. [`processWorker`](https://github.com/bbc/waveform-data.js/blob/d720259d882ebbc5bbf1a6029820582a415979d2/lib/builders/audiodecoder.js#L6) - This uses [inline-worker](https://www.npmjs.com/package/inline-worker) to produce the waveform data using a Web Worker. Does the [message handler function](https://github.com/bbc/waveform-data.js/blob/d720259d882ebbc5bbf1a6029820582a415979d2/lib/builders/audiodecoder.js#L23) get called?

I noticed another strange issue with your example: on Chrome (and Edge) 89 on Windows, the audio and the playhead seem out of sync: I can hear the piano note before the playhead reaches the start of the waveform. Sometimes it's fine, but other times it's visibly out of sync.

**Comment by OmarShehata** [comment]
Thank you so much for the detailed breakdown of where to look @chrisn ! I started to debug this and discovered it's actually fixed in master. A git bisect shows this is the commit that fixed it: https://github.com/bbc/peaks.js/commit/3131056f0c0ecb2f906cdab1b7f6a107006bfcd3. 

So I can `git checkout 3131056f0c0ecb2f906cdab1b7f6a107006bfcd3` and `npm run build` and run it on iOS through Browserstack and it works, and in the commit right before that it does not. 

I think we can close this issue now. For completeness, when testing with the latest bad commit (https://github.com/bbc/peaks.js/commit/e7e8d5386bd9bf76506f9f011b4f693c05b19c81), `mediaSourceUrl` is an empty string, and the `player.canplay` event does NOT fire (even though the event listener code does run, confirmed that else block runs).

Let me know if there's anything else that'd be helpful here to provide or feel free to close the issue. Thank you so much!
