### ISSUE TITLE
Center line on waveform display?

### ISSUE THREAD

**Issue by shealan** [bbc/peaks.js#374]
![image](https://user-images.githubusercontent.com/74932/110200349-92139480-7eb1-11eb-8dba-72f0ada31ef5.png)

Is it possible to add a center line on the waveform display? On waves with some silent parts the waveforms look a little odd floating in space on their own. A feint central line would provide a more DAW type display.

I can't seem to find a setting that allows for this.

Amazing library, thank you so much for making it open source ♥️

**Comment by bsnman** [comment]
It would also be great if there's an option to draw center line if silence.

Right now I have audio that last <1 second, and I could see the individual waves.
I don't want it to have a center line all the way, just the silence portion of the waves.

**Comment by chrisn** [comment]
I just made a simple change to fix this, it'll be available in the next release.
