### ISSUE TITLE
Cue Events are only triggering when seeking, and not when playing

### ISSUE THREAD

**Issue by richardbonneau** [bbc/peaks.js#380]
I am using React and was able to make it work on the React example project by simply setting the emitCueEvents to true in the options and defining a 'segments.enter' event receiver. 

However, in my actualy project, it is only working when seeking on a segment and after hours and hours of comparing the test project and mine, I can't find a single difference. 

Could this be because I am using Hooks and the test project is using Classes? Any pointers or extra info I could provide to help with this issue? Thank you.

**Comment by chrisn** [comment]
Sorry, this was a bug introduced in the last release, and nothing at all to do with your React code. I have just fixed the bug, so please update to v0.24.1.

**Comment by richardbonneau** [comment]
@chrisn Wow! it was worth it to post my issue on here. It works, thank you so much.

**Comment by chrisn** [comment]
Thank you for reporting it! And sorry again for the time you had to spend trying to debug this.
