### ISSUE TITLE
mediaUrl required in setSource options in TypeScript?

### ISSUE THREAD

**Issue by noaLeibman** [bbc/peaks.js#384]
Hi!
I have the latest version (0.25.0) installed in a TypeScript project.
I saw that the `mediaUrl` property is still required on `SetSourceRequiredOptions` even though this was changed before, was peaks.js.d.ts not updated?
Thanks:)

**Comment by chrisn** [comment]
It seems that way, thanks for reporting this.  (I need a better way of updating and testing the TypeScript definitions, it's a constant source of issues...)
