### ISSUE TITLE
Using two instances of peaks.js on the same page

### ISSUE THREAD

**Issue by amitgur** [bbc/peaks.js#385]
I would like to use peaks to coordinate between two mono sound files. Is it possible to create two instances of peak on the same page. I tried it and it's not working
Any help with that?

**Comment by chrisn** [comment]
It is possible to create two independent Peaks instances for two separate audio or video elements. I'd need more information to be able to help, what have to tried?

**Comment by amitgur** [comment]
Just checked it out, it's working. thanks
