### ISSUE TITLE
`peaks.ready` event being fired when not ready?

### ISSUE THREAD

**Issue by ffxsam** [bbc/peaks.js#388]
I have a method that gets called when `peaks.ready` is emitted, which makes sure the waveform is fully zoomed out:

```ts
    scaleToFit() {
      const zoomview = this.peaks.views.getView('zoomview');

      if (!zoomview) return;
      const maxScale = zoomview._getScale(this.peaks.player.getDuration());
      console.log('set scale to', maxScale);

      if (maxScale === Infinity) return;
      zoomview!.setZoom({ scale: maxScale });
    },
```

Randomly, I'll get the error `RangeError: You should provide either a resampling scale or a width in pixel the data should fit in.` because `maxScale` comes back as `NaN`, because `this.peaks.player.getDuration()` returned `NaN`.

If Peaks was ready, as the event would indicate, why would `getDuration()` return `NaN`?

**Comment by ffxsam** [comment]
I don't remember why I'm not using `zoomview.setZoom({ seconds: 'auto' })`. I'm assuming there was some good reason for it!

**Comment by ffxsam** [comment]
Ok, so this is interesting:

When loading a track for the first time, `loadedmetadata` fires. But the second time I load up the waveform, `loadedmetadata` doesn't fire (even though the audio element is being destroyed when I navigate away from the page that has the waveform). In fact, nothing from the audio element fires that tells me it's ready and has a duration. So, before I do anything with the waveform, I wait for at least two dependencies:

```js
    this.$refs.audio.addEventListener('loadedmetadata', () => {
      ++this.readyDependencies;
    });
    this.peaks.on('peaks.ready', () => {
      ++this.readyDependencies;

      // If duration is already available, we won't get loadedmetadata event
      if (this.$refs.audio.duration > 0) {
        ++this.readyDependencies;
      }
    });
```

And when `this.readyDependencies >= 2`, then I execute:

```js
      zoomview.fitToContainer();
      zoomview.setZoom({ seconds: 'auto' });
```

It's hacky, and I'm not a fan of it.. 😄 but it works.

**Comment by chrisn** [comment]
Just to check, are you using pre-computed waveform data, not Web Audio?

It may be possible change `peaks.ready` so it waits for the audio element to also be ready. We do this already with `.setSource()` - which you may want to try if you're changing the audio without reloading the page.

**Comment by ffxsam** [comment]
Yessir, I'm loading waveform data independently from the mp3 audio file.

The funny thing is, the component that Peaks and the `<audio>` element are in is destroyed every time the player is closed, so I would think playing another track would start totally fresh.

Here's a question: in the player, I have `<audio :src="trackUrl"/>` to feed the mp3 URL to the audio element. Should I not do this, and instead set it via `peaks.setSource(this.trackUrl)` and leave `src` empty in the audio element?

**Comment by chrisn** [comment]
Peaks.js v2.0.0 should fix this, as it now waits for the media element duration to be valid before initialising the waveform views, and so the `Peaks.init()` callback and `peaks.ready` events should now fire when the duration is valid.
