### ISSUE TITLE
Moving labeltext in overview view

### ISSUE THREAD

**Issue by jamesb93** [bbc/peaks.js#389]
I would like to either disable, but ideally move the label text that is produced when scrubbing through the overview view. At the moment it gets obfuscated by the waveform itself which is not ideal. What is the way to approach solving this with the API?

![image](https://user-images.githubusercontent.com/13281862/119651010-67840880-be1c-11eb-9ac0-bda8f8d6bd65.png)

**Comment by chrisn** [comment]
Would [this](https://github.com/bbc/peaks.js/blob/master/customizing.md#createsegmentlabeloptions) work for you?

**Comment by jamesb93** [comment]
> Would [this](https://github.com/bbc/peaks.js/blob/master/customizing.md#createsegmentlabeloptions) work for you?

Yep this is great. Thanks for the pointer the config stuff is a little nested and I didn't see it but this looks approachable enough :)
