### ISSUE TITLE
Conditional customization of markers is tricky

### ISSUE THREAD

**Issue by jdelStrother** [bbc/peaks.js#391]
We use custom markers in the zoomview, but not in the overview. It's pretty ugly to accomplish this:

```ts
    Peaks.init(peaksOptions, (err, peaks) => {
        let options: Peaks.PeaksOptions = (peaks as PeaksPrivate).options;
        var originalCreatePointMarker = options.createPointMarker!;
        // @ts-expect-error createPointMarker isn't marked as writable
        options.createPointMarker = function (options) {
          if (options.view === "overview") {
            // this is the marker used by the overview layer
            return originalCreatePointMarker(options);
          }
          // this is the marker used by the zoomview layer
          return new CustomMarker({ ...options, ...markerOptions });
        };
```

It doesn't look like `MarkerFactories` is exported anywhere, or we could just use something like:

```ts
    Peaks.init({
      createPointMarker: function (options) {
          if (options.view === "overview") {
            // this is the marker used by the overview layer
            return MarkerFactories.createSegmentMarker(options);
          }
          // this is the marker used by the zoomview layer
          return new CustomMarker({ ...options, ...markerOptions });
        };
```

WDYT to exposing those MarkerFactories somehow, so we can either import them when importing peaks (`import Peaks, {MarkerFactories} from "peaks.js"`), or passing them into the createPointMarker function so we can manually call them from in there?

**Comment by chrisn** [comment]
I didn't anticipate this use case - the idea was that if you want custom markers for one view, you'd also want them for the other.

**Comment by jdelStrother** [comment]
Given how simple the overview layer's default marker rendering is, for this case it's probably easier to improve our custom marker so that it can be used in both places. I'll have a think if there's other cases where that's not so easy.

**Comment by chrisn** [comment]
As an alternative to exposing MarkerFactories, I guess we could have `createPointMarker` return a string `"default"` if it wants the Peaks.js default marker

**Comment by jdelStrother** [comment]
Now that I've dug into our custom marker code some more, we should have just made our custom markers deal with being drawn in the overview, rather than trying to use one marker in the zoomview & another marker in the overview. I think your `"default"` suggestion might be useful for some people, but I'm happy to close this feature request if you like.

**Comment by chrisn** [comment]
Thanks. I probably wouldn't implement this unless change someone needs it, so happy to close for now and review in future.
