### ISSUE TITLE
Possibility to playback a point (e.g. with a click)?

### ISSUE THREAD

**Issue by rowild** [bbc/peaks.js#403]
Is it possible to playback a click sound for each set point, when playing back the audio file? Also, when the playhead passes a point, is it possible to assign some kind of visual feedback to the point (e.g. a change in color)?

**Comment by chrisn** [comment]
I think Peaks.js provides all the extensibililty points you need to implement this. Take a look at [Cue Events](https://github.com/bbc/peaks.js#cue-events) and [`point.update()`](https://github.com/bbc/peaks.js#pointupdate-time-labeltext-color-editable--) in the documentation. Playing a click sound or changing the marker colour would be your application's responsibility though.
