### ISSUE TITLE
Can I use peaks.ready event for chunked dat file?

### ISSUE THREAD

**Issue by adi518** [bbc/peaks.js#404]
I'm loading a chunked dat file into my Peaks instance. Can I use the `peaks.ready` event to ensure that Peaks is ready and fully loaded with the dat file?

**Comment by chrisn** [comment]
I'm not sure what you mean by a chunked dat file - but yes, Peaks emits the `peaks.ready` event when it's ready and the dat file has been loaded. You can also use the `Peaks.init()` callback function.

**Comment by adi518** [comment]
So the init callback is equivalent to `ready` event?

**Comment by chrisn** [comment]
Yes. The API originally only had the event and the callback was added later. The event is still there mostly for backwards compatibility.
