### ISSUE TITLE
How to test in e2e test?

### ISSUE THREAD

**Issue by adi518** [bbc/peaks.js#405]
This question may seem out of place, but actually, it might not. I'm testing my app using Cypress and I'm running into racing condition issues and possibly triggering the wrong mouse/pointer events. Can you tell which events (exactly) trigger segment creation? I'm currently trying to do this (without much success):

```js
cy.get('#zoom-container')
  .trigger('mousedown', { x: centerX, y: centerY })
  .trigger('mousemove', { x: centerX + 150, y: centerY })
  .trigger('mouseup');
```

**Comment by chrisn** [comment]
It's a good question, as we don't have good test coverage for mouse and keyboard input yet.

Creating a segment is only done by calling the `peaks.segments.add()` function, it's not possible to do it using only mouse input.

**Comment by adi518** [comment]
We actually forked it and added this functionality (not me specifically), so I should actually look at the fork now, rather than the original code, heh.

**Comment by chrisn** [comment]
OK, let me know if I can be of any more help. By the way, we're planning to add segment creation using mouse input, see https://github.com/bbc/peaks.js/discussions/373#discussioncomment-820978.

**Comment by adi518** [comment]
I made some progress, but I'm getting `NaN` in `time` argument for a `zoomview.drag` event.

**Comment by chrisn** [comment]
Is `zoomview.drag` specific to your fork? It's not in our [list of events](https://github.com/bbc/peaks.js#events).

**Comment by adi518** [comment]
I couldn't find it in the source here, so I guess it's part of the fork. I did find this though: https://github.com/bbc/peaks.js/blob/093d78d2bf2c49c0c3a96a2583286a6ead47a578/src/waveform-zoomview.js#L139

I'm near certain that's the `time` argument that gets passed as `NaN`.

**Comment by chrisn** [comment]
Can you reproduce the issue in this repo? I can't really help with debugging forks, sadly.
