### ISSUE TITLE
Zoomview is not generated since 0.26 when using an arraybuffer

### ISSUE THREAD

**Issue by richardbonneau** [bbc/peaks.js#409]
Was there any changes made that would render my arraybuffer incompatible? I simply updated my working project from 0.24 to 0.26 and now only the overview is showing. I don't see any errors in the browser console or react terminal.

Any pointers or tips that could point me in the right direction? Thank you.

![nozoom](https://user-images.githubusercontent.com/36018812/126358383-eaa8890c-52cf-4929-a30a-dfc10c212af0.PNG)

**Comment by chrisn** [comment]
Have you looked at the [change log](https://github.com/bbc/peaks.js/blob/master/CHANGELOG.md)?

**Comment by richardbonneau** [comment]
@chrisn Hey Christ thanks for the swift answer. I took a second look at the changelog to make sure I didn't miss anything. I am not using the height parameter and the views are inside the containers key. I provided you with my init code maybe I am missing something?

![image](https://user-images.githubusercontent.com/36018812/126491931-11aa3ea7-0315-4af5-8751-084746ed6876.png)

**Comment by chrisn** [comment]
I don't see a problem with the .dat file, because the overview waveform looks right - but I'm happy to test it locally if you can share it. I tried your options in my [React demo app](https://github.com/chrisn/peaksjs-react-example) and it's working OK. Are there any errors in the console?

**Comment by richardbonneau** [comment]
@chrisn no errors at all! I will send you some details via email. Thanks for taking the time!

**Comment by richardbonneau** [comment]
The problem (found by chrisn) was that you need to provide a height via CSS to your overview and zoomview containers. We can now close this issue. Thanks Chris!
