### ISSUE TITLE
Overlaying the selected segment

### ISSUE THREAD

**Issue by purushottam05** [bbc/peaks.js#413]
![overlay](https://user-images.githubusercontent.com/55759055/138456919-45429f96-8a95-4fed-bc57-0f57de6287fb.png)
 
Hello, I'm not sure how to highlight the selected segment as shown in the picture. How can I do that?

Thank you.

**Comment by rowild** [comment]
I would like to upvote this idea of having a waveform-independent way to display a segment. 

I love the current solution very much, and it should definitely stay the standard solution! However, in scenarios, where the waveform must be hidden, an alternative solution would be most welcome.

ATM it even seems to be a very delightful idea to have the option at hand to draw both versions at the same time... but I know: that's pushing it. :-)

**Comment by chrisn** [comment]
Please take a look at v3.0.0 beta, I think this allows you to do what you need.
