### ISSUE TITLE
[docu] unpgk link broken

### ISSUE THREAD

**Issue by rowild** [bbc/peaks.js#416]
The docu links to this CDN:
https://unpkg.com/peaks.js/dist/peaks.js

But unpgk complains:
Cannot find "/dist/peaks.js" in peaks.js@0.26.0

Without the `/dist` the "normal" peaks can be found:
https://unpkg.com/peaks.js@0.26.0/peaks.js

but that one is not minimized.

(I think the `dist` folder has to be published, too, for unpgk...?)

Also, if `peaks.js` is included via script tag, what about `Konva` and `waveform-data`? Do they have to be included via script tag, too, or does `peaks.js` take care of that in this case?

**Comment by rowild** [comment]
@chrisn Just a short feedback after some days using your rollup version: Haven't tested everything yet, but so far everything works very smooth. :-) Thank you!

**Comment by chrisn** [comment]
Thank you. I have just published v0.27.0 to npm.
