### ISSUE TITLE
[Documentation] Link not working

### ISSUE THREAD

**Issue by rowild** [bbc/peaks.js#422]
Right ABOVE this header

https://github.com/bbc/peaks.js/blob/master/customizing.md#marker-api

there is a sentence saying "Refer to the <link-that-does-not-work>marker methods</link-that-does-not-work>". This link is not working. Is it supposed to jump to "Marker API" or somewhere different? (I'll provide a PR, if you confirm.)

**Comment by chrisn** [comment]
Yes, it should link to Marker API. Thank you!

**Comment by rowild** [comment]
Thank you!
Closing with PR #423
