### ISSUE TITLE
Tone.js player demo produces no sound

### ISSUE THREAD

**Issue by chrisn** [bbc/peaks.js#451]
The [external player demo page](https://github.com/bbc/peaks.js/blob/fa4ba2a3a7eee05601fc78c952683b79d77adb4b/demo/external-player.html) doesn't produce any sound. This page uses Tone.js but I'm not familiar with it. Does anyone have a suggestion for how to fix this?

**Comment by suterma** [comment]
I can double this. No sound with this example on Chrome, on Ubuntu Linux. All others worked just fine.
