### ISSUE TITLE
zoomview not update setsource

### ISSUE THREAD

**Issue by teswk** [bbc/peaks.js#452]
When manual set the source using audio file .. overview is updated with new audio but zoomview not updating. can you help me on that

**Comment by chrisn** [comment]
This was a bug introduced in the waveform cache feature added in v0.28.0. It's now fixed, so please update to v2.0.0. You can see details of the changes [here](https://github.com/bbc/peaks.js/blob/master/CHANGELOG.md) and our [migration guide](https://github.com/bbc/peaks.js/blob/master/doc/migration-guide.md) in case changes are needed to your code.
