### ISSUE TITLE
Mousewheel scroll not working

### ISSUE THREAD

**Issue by chrisn** [bbc/peaks.js#454]
I've received a bug report that mousewheel scrolling isn't working in some cases. On one user's system it seems that the mousewheel changes the `deltaX` value rather than `deltaY` in [`wheel`](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent) events. This user has MacOS (12.4), but I don't know if this issue is Mac specific. The `WheelEvent` values are controlled by the host OS and possibly mouse/trackpad driver settings, so I think this is browser independent. I haven't been able to reproduce this locally.

On my Windows laptop, the current behaviour is:

- Vertical trackpad gesture scrolls the page
- Horizontal trackpad gesture (with pointer over the waveform view) scrolls the waveform
- Shift + vertical trackpad gesture (with pointer over the waveform view) scrolls the waveform
- Shift + horizontal trackpad gesture scrolls the page
- Mousewheel scrolls the page
- Shift + mousewheel (with pointer over the waveform view) scrolls the waveform

There is a proposed change on [this branch](https://github.com/bbc/peaks.js/tree/wheel-events), which implements this behaviour:

- Vertical trackpad gesture scrolls the page
- Horizontal trackpad gesture (with pointer over the waveform view) scrolls the waveform
- Shift + either horizontal or vertical trackpad gesture (with pointer over the waveform view) scrolls the waveform
- Mousewheel scrolls the page
- Shift + mousewheel (with pointer over the waveform view) scrolls the waveform

@ffxsam, @jdelStrother, @tscz, @rowild Do you see any issues making this change?

**Comment by jdelStrother** [comment]
Nope, sounds good. And I can confirm that shift-mousewheel on mac currently doesn't scroll the waveform, and that that branch fixes it.

**Comment by chrisn** [comment]
Now fixed on master.

**Comment by jdelStrother** [comment]
I don't love the idea of vertical trackpad scrolls causing the waveform to scroll horizontally, that sounds pretty weird to me. However, I don't see any distinguishing features in the `wheel` event to tell the difference between a mousewheel and a vertical trackpad gesture 😕 

<img width="771" alt="image" src="https://user-images.githubusercontent.com/2377/184716328-0f46cb4d-4d0a-4381-bed6-d0042945ace8.png">

**Comment by chrisn** [comment]
Yes, I agree. What I might do is add an option for this particular user and leave the default as it currently is, so they can try it out.

**Comment by ffxsam** [comment]
My two cents:

Since a Peaks waveform could likely exist on a page with other content, any sort of scroll action should be combined with shift to actually scroll (or zoom) the waveform. This obviously prevents a user who's scrolling down the page from getting "trapped" in the Peaks canvas area. This is a common pattern used by other embeddable widgets that use wheel/scroll (e.g. Google Maps).

Furthermore, there should be a lock-in effect for horizontal/vertical scrolling, so if a user starts doing shift + vertical scroll and the Y delta is greater than a certain # of pixels, the user is locked into a zoom action. That way, if their gesture drifts a bit to the left or right, it won't start scrolling the waveform.

**Comment by chrisn** [comment]
Thanks Sam, that's helpful.

**Comment by rowild** [comment]
I only used peaks in the context of position:absolute & overflow:hidden pages. Using peaks' waveform scrolling with SHIFT as @ffxsam describes is a good solution for pages with other content. But if there is a chance to not have to use SHIFT on absolute positioned pages, so peaks can be used like a SAW is used, that would be most welcome.

**Comment by ffxsam** [comment]
Yeah, agreed. An option to set the behavior would be ideal.

**Comment by chrisn** [comment]
Thank you all, just need to think of a good name for the option. The default will remain as it is today.

**Comment by chrisn** [comment]
v2.0.4 now released, which allows the waveform to be scrolled without pressing Shift:

```javascript
const view = instance.views.getView('zoomview');
view.setWheelMode('scroll', { captureVerticalScroll: true });
```
