### ISSUE TITLE
Marking event listeners as passive (or not) to get rid of a violation warning

### ISSUE THREAD

**Issue by suterma** [bbc/peaks.js#459]
To optimize scrolling performance, [passive event listeners can be declared with an option](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md). Currently, the declaration is missing, and a warning is displayed in recent Google Chrome browsers. See the below example from the https://candeogi.github.io/peaks-vue-demo/ by Giovanni Candeo.

![Screenshot from 2022-08-22 22-58-53](https://user-images.githubusercontent.com/11473920/186018022-c949bbaf-4e06-4370-afc9-f8142c4b0c1f.png)

To get rid of the warning, the appropriate value for the option should be chosen when the event listener is added.

Example (from https://github.com/slipmatio/control-knob/blob/main/src/ControlKnob.vue#L278)

      element.addEventListener('wheel', wheelListener, { passive: true /*or false, depending on requirements*/ })

For peaks.js I would guess that touch or mouse events should be passive in this sense, in case the intention was to NOT scroll the page, but the waveform.

**Comment by chrisn** [comment]
Thank you for mentioning this. The warnings come from Konva, and related issues have raised there: https://github.com/konvajs/konva/issues/260, https://github.com/konvajs/konva/issues/1382. In some cases Peaks.js does allow the page to scroll, this is discussed in https://github.com/bbc/peaks.js/issues/454.

**Comment by suterma** [comment]
I now have raised the issue directly on the konvajs repo and will therefore close this issue here.

**Comment by chrisn** [comment]
Thanks. There are some places where Peaks.js calls `window.addEventListener` that may be worth looking at: https://github.com/bbc/peaks.js/blob/master/src/mouse-drag-handler.js#L94

**Comment by suterma** [comment]
Ok, then it might be a good idea to keep this open too. I'll leave it to you as the maintainer to proceed with this issue. I am currently not able to contribute code in a meaningful way here.
