### ISSUE TITLE
Visualizing all audio and zooming on the same canvas

### ISSUE THREAD

**Issue by katcipis** [bbc/peaks.js#46]
Is there a way to show only one waveform and zoom on it instead of always having two ? I have some space constraints and it would be awesome to use only one waveform (one canvas) to zoom in/out and show the entire file.

All the examples always shows two, so i don’t know if it is possible.

If it is not possible right now, would it be an welcomed addition ? :-)

**Comment by chrisn** [comment]
Release 0.10.0 allows you to create a single waveform view. Please see https://github.com/bbc/peaks.js/blob/master/demo/zoomable-waveform.html for an example.
