### ISSUE TITLE
Overlay segment feature not available in latest plugin version 2.1.0 ?

### ISSUE THREAD

**Issue by Arjun021** [bbc/peaks.js#468]
I checked the demo of overlay segments and it's fulfilling my requirements. I installed the latest version of peaks.js (2.1.0) and followed the same code given in the demo. But after using same code, still I am not able to get the overlay segment as displayed in the demo. 

Is there anything I am missing in this or is the overlay segment feature not yet available in the latest version?

```
let options: any = {
      zoomview: {
        container: document.getElementById('zoomview-container'),
        showPlayheadTime: true,
      },
      overview: {
        container: document.getElementById('overview-container')
      },
      mediaElement: document.getElementById('audio'),
      dataUri: {
        arraybuffer: this.spectrographURL,
      },
      waveformCache: true,
      showPlayheadTime: true,
      zoomLevels: [256, 512, 1024, 2048, 4096],
      segmentOptions: {
        style:                     'overlay',
        waveformColor:             '#ff851b',
        overlayColor:              '#ff0000',
        overlayOpacity:            0.3,
        overlayBorderColor:        '#ff0000',
        overlayBorderWidth:        2,
        overlayCornerRadius:       5,
        overlayOffset:             40,
        overlayLabelAlign:         'left',
        overlayLabelVerticalAlign: 'top',
        overlayLabelPadding:       8,
        overlayLabelColor:         '#000000',
        overlayFontFamily:         'sans-serif',
        overlayFontSize:           14,
        overlayFontStyle:          'normal'
      },
      createSegmentLabel: function() { return null; },
```

**My end result is coming as per below**
<img width="946" alt="image" src="https://user-images.githubusercontent.com/90953201/199812591-bae475c9-755a-4feb-80dd-0ce1f596908d.png">

**The expected result is as per below**
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/90953201/199812840-df46b637-01bf-45ae-8f79-7cc38e641115.png">

**Comment by chrisn** [comment]
This feature isn't in a release version yet, the latest v2.1.0 release doesn't include it. I'm planning to make a beta version soon. There's still some work to do on documentation.

**Comment by Arjun021** [comment]
Okay @chrisn , thanks for the update. This feature is really helpful. Hope it gets released soon 😃

**Comment by chrisn** [comment]
It's coming soon, yes! I'm very interested in your feedback and suggestions, or if you find any issues.

**Comment by alxpsr** [comment]
Looking forward ^_^

**Comment by chrisn** [comment]
Version 3.0.0-beta.0 is now released, which includes overlay and draggable segments. There may be bugs, feedback welcome!

```
npm install peaks.js@beta
```

**Comment by chrisn** [comment]
I'll close this, but please raise new issues if you have suggestions.
