### ISSUE TITLE
Retrieve the browser-generated waveform data as json to send back to the server?

### ISSUE THREAD

**Issue by iandoesallthethings** [bbc/peaks.js#473]
I'd like to implement automatic updates for new audio files. I.e. the first user to access a file would have to wait while the audio api generates the waveform, but then we just send the json back to the server and cache it there until the next time the audio file changes.

Is there a way to get the waveform data back out once it's generated in the browser?

**Comment by chrisn** [comment]
You can get the waveform data using `peaksInstance._waveformData`. But this is private data, so not recommended. I'll add a documented API, so in a future version you'll be able to call `peaksInstance.getWaveformData()`.

Refer to the [API documentation](https://github.com/bbc/waveform-data.js/blob/master/doc/API.md) for details of how to use `_waveformData`.

**Comment by iandoesallthethings** [comment]
Lovely, thank you!
