### ISSUE TITLE
overview play time selection not working (chrome only)

### ISSUE THREAD

**Issue by Goddard** [bbc/peaks.js#475]
Not sure if this is a new development, but I don't really know as I have only been using peakjs for a short time.  

In firefox selecting a time from the overview works fine.  It jumps to that point, but in Chrome it doesn't seem to work.  I can see the cursor move to that point in time on the wave form I clicked, but then it just jumps right back to the start in chrome(google chrome and edge were tested).

**Comment by chrisn** [comment]
The usual cause is if there's a problem fetching the audio. Clicking the overview causes the media element to seek, so if the audio is not buffered, the seek fails, and the playhead jumps back to the start.

**Comment by Goddard** [comment]
When I have had instances where the audio wouldn't load the waveform graphic wouldn't display at all.  In this case I think it is loading fine.  I haven't been able to figure out why this is happening yet.  The player plays the audio just fine and on firefox it works great.  I will see if I can't reproduce in a open site to show.

**Comment by chrisn** [comment]
Thank you, that will make it easier to investigate. We have had a similar issue before, https://github.com/bbc/peaks.js/issues/233, could it be this?
