### ISSUE TITLE
Problem with dragend event

### ISSUE THREAD

**Issue by NinjaCoderDotCom** [bbc/peaks.js#480]
Hi 
I am using your demo of V3.0.0.6. When I log `event.segment.endTime` inside `segments.dragend` and drag the right of one segment and match it to the end as shown in attached media below. The end time should be same as the start time of next segment. Please check the media once and get back to me.
As you can see in the video attached, I first drag the end of segment and then took my mouse cursor across the next segment and leave the click of mouse which logs the time in console. Then, I click on log segment time provided in the example. You can see that the start time of second segment and end time of first segment that I logged is not same while it should be. Please help.

https://user-images.githubusercontent.com/107407402/224242675-95494c0f-39d9-44b6-8fb8-6fff8cce8138.mp4

.
.
**Screenshot of opted options**

![Screenshot from 2023-03-10 12-11-43](https://user-images.githubusercontent.com/107407402/224244062-8738459c-4e65-49bd-b740-0a10714eadb7.png)

**Comment by chrisn** [comment]
Thank you for reporting this. I'll investigate.

**Comment by chrisn** [comment]
I have released v3.0.0-beta.7 which should fix this issue. Thanks again for reporting it, your feedback is really valuable!
