### ISSUE TITLE
segment.update() seems not working

### ISSUE THREAD

**Issue by coleea** [bbc/peaks.js#481]
version that i use : 3.0.0-beta.7

hi.

I made some code that changes labelText of Segment. details are below.

```
peaks?.on('segments.click', function(segmentEvt) {
        segmentEvt.segment.update({                   
          labelText : "I changed labelText",
        })
```
I expected that labelText of Segment will be changed. but nothing happens. 

in console.log, nothing shows. so I can't get any feedback. I don't know about what's wrong?

interesting thing is that update callback function that I wrote in segments array of PeaksOptions is called

```
const options : PeaksOptions  = {
      segments : [
        {
          startTime : 2 ,
          endTime : 5,
          update : (e) => {console.log("this is triggered. when I call  segmentEvt.segment.update");},
          labelText : "before modified",
          color : "#ff0000",
          id:"987",
          editable : true,
        }
      ]
};
```

What I am missing? 
Thank you

**Comment by chrisn** [comment]
In your `segments` array, you have an object with an `update` property:

```js
update : (e) => {console.log("this is triggered. when I call  segmentEvt.segment.update");},
```

This replaces the library's internal `Segment.update()` method, which would cause the segment to be redrawn.

The segment should change the label text if you remove this `update` property.

**Comment by coleea** [comment]
thank you @chrisn  for your answer. 

I already did what you are suggested. As I know, update property is "required" in typescript options.
So when I delete update function, type error occurs
![_제목 없음](https://user-images.githubusercontent.com/7471674/227402077-8e8f9537-0376-4e8f-9572-3ab873c1eb1e.png)


ts2741 error  2741 : Property is missing in type.
So I cannot delete update function.
Is It bug ? 

Thank you again.

**Comment by chrisn** [comment]
I see, thank you! There was a bug in the TypeScript declarations. The `update` property should not be required.

**Comment by chrisn** [comment]
The fix is available in v3.0.0-beta.8.

**Comment by coleea** [comment]
@chrisn , thank you very much !

**Comment by coleea** [comment]
in version  v3.0.0-beta.8, this bug is fixed ?
I'm still experiencing the same error

**Comment by chrisn** [comment]
It should be fixed, yes, but the type has changed:

```typescript
const segments: SegmentAddOptions[] = [
  {
    startTime: 2,
    endTime: 5,
    labelText: "hello"
  }
];
```

**Comment by coleea** [comment]
I got it. thank you @chrisn ! everybody should know this.

**Comment by chrisn** [comment]
Thank you, your feedback is really helpful!
