### ISSUE TITLE
Issue with dragend event

### ISSUE THREAD

**Issue by NinjaCoderDotCom** [bbc/peaks.js#488]
Hi,
I am trying to check when does your dragend and dragstart event fires. So, the dragend event is also fired when I drag the starting of segment, co-incide it with the previous segment and release it. Same is happening if I drag the ending of the segment, matching it with the next segment and releasing it. According to me, these events should not fire together like this. Also, when you drag and drop the segment then sometimes dragstart is getting fired sometime dragend. In this case, either both of them should get fired or neither of them should.

_**Screenshot 1: Zoomview with settings**_
![ss1](https://user-images.githubusercontent.com/107407402/236740709-69e29ca7-84cb-497e-aefa-c4824786b147.png)

_**Screenshot 2: Dragging a segment's start and co-inciding it with the previous segment's end**_
![ss2](https://user-images.githubusercontent.com/107407402/236741193-6fde83ba-b02e-4ff5-adac-a90b0a3d2470.png)

_**Screenshot 3: Screenshot of console showing both events getting fired (along the screenshot of code sample).**_
![ss4](https://user-images.githubusercontent.com/107407402/236741332-d1739bdb-7007-4aff-8476-0b7573ae3f1d.png)
![ss3](https://user-images.githubusercontent.com/107407402/236741212-f0736e8c-4ffd-4619-ba44-6b383a551bff.png)

Do correct me if I am mistaken.
**P.S-** Tested it on v3.0.0-beta.8

**Comment by NinjaCoderDotCom** [comment]
Hi @chrisn 
Thank you for helping me out regarding the both of events. I think through this explanation now all of my doubts and problems will be solved.

**Comment by NinjaCoderDotCom** [comment]
Hi @chrisn 
I have one more doubt that how can I identify whether whole segment is being dragged or just start/end is being changed?

**Comment by chrisn** [comment]
The events currently don't give you that information, the events are the same when dragging the whole segment, and when just dragging the start or end. The `startMarker` flag in the event is always `false` when dragging the whole segment.

**Comment by NinjaCoderDotCom** [comment]
The `startMarker` flag is also false if you drag and drop the endtime of segment. I need something from which I can know that if I am dragging the whole segment or just resizing it by changing the starting and ending time.

**Comment by NinjaCoderDotCom** [comment]
@chrisn 
The startMarker flag is also false if you drag and drop the endtime of segment. I need something from which I can know that if I am dragging the whole segment or just resizing it by changing the starting and ending time.

**Comment by chrisn** [comment]
We can add an option to the events to indicate that, e.g.,

```
this._peaks.emit('segments.dragged', {
  segment: this._segment,
  startMarker: false,
  marker: true,
  evt: event.evt
});
```

where `marker` is `true` when resizing (i.e., either the start marker or end marker is being dragged) and `false` when dragging the whole segment.

**Comment by NinjaCoderDotCom** [comment]
Yeah, that will be very good to identify between both events. When can we except the release of new version along with this change?

**Comment by chrisn** [comment]
Is it OK it close this issue?
