### ISSUE TITLE
Suggestion: Addition of mouse events for zoomview.

### ISSUE THREAD

**Issue by NinjaCoderDotCom** [bbc/peaks.js#499]
Hi, @chrisn 

I think there is a need to add a few primary mouse events, the same as segment mouse events like mousedown, mouseup, and mousemove, so that the functionality of making segments via drag and drop can be implemented. A video explaining the same is attached below.

https://github.com/bbc/peaks.js/assets/107407402/db2bfb6c-2930-442e-98fe-5cac93492b0d

**Comment by chrisn** [comment]
Yes, I definitely want to add the ability to create segments by drag and drop. There's a similar issue here: https://github.com/bbc/peaks.js/issues/190

**Comment by chrisn** [comment]
Some work in progress...

https://github.com/bbc/peaks.js/assets/57790/b885ca09-9bca-42f8-871d-adfe64ad3ad4
