### ISSUE TITLE
WaveformData.resample(): Zoom level xxx too low, minimum: xxx

### ISSUE THREAD

**Issue by tanguy-lf** [bbc/peaks.js#500]
This happen when changing the waveform source, with very short waveform.
Like in #104 

I can do a PR if you need.

**Comment by chrisn** [comment]
Thank you, and for offering to create a PR. I have fixed the error in [#328187](https://github.com/bbc/peaks.js/commit/3281877c38208aa7415e81de423321423ec88541).
