### ISSUE TITLE
Render points without audio data present

### ISSUE THREAD

**Issue by nickbetsworth** [bbc/peaks.js#506]
For my use case, I am attempting to render pre-computed waveform data and points _without_ forcing the user to load the audio data itself.

This appears to work as expected in terms of rendering the waveform data:
<img width="408" alt="image" src="https://github.com/bbc/peaks.js/assets/9088572/7d0a9470-ca76-4497-897e-af2f93b049d9">

However, I am facing issues adding points when there is no audio data associated with the peaks distance. The waveform is rendered correctly, but the points are not rendered unless there is audio attached.

Initialisation:
```js
const options = {
  overview: {
    container: document.getElementById('overview-container')
  },
  mediaElement: document.getElementById('audio'),
  dataUri: {
    json: 'waveform.json'
  }
}

Peaks.init(options, function (err, instance) {
    instance.points.add([
        {time: 0, labelText: 'Label A'},
        {time: 1, labelText: 'Label B'},
        //...
    ])
})
```

DOM
```html
<div id="overview-container"></div>
<audio id="audio"></audio>
```

Interestingly, if I attach an audio clip that is shorter than the waveform, I am then able to see any points that precede the end of the audio clip. But I am unable to see any points on the waveform that occur after the duration of the audio clip. (This isn't a real use case of mine, but thought it was an interesting observation. It seems the points are almost reliant on the audio data as opposed to the waveform)

An example of what this looks like:
(This clip should have ~20 points spread out across the 6 minute waveform. But only the first two points are visible, as they occur prior to the 60 second audio clip that is attached)
<img width="411" alt="image" src="https://github.com/bbc/peaks.js/assets/9088572/42b17180-1a66-4690-bbcf-abca4d8b1f5d">

Many thanks

**Comment by chrisn** [comment]
Thanks for reporting this. The overview waveform was using the audio duration rather than the total duration visible, when selecting the points to draw.

**Comment by nickbetsworth** [comment]
Hi Chris,

Many thanks for the exceptionally quick response and resolution. I'll give it a test later this evening

**Comment by nickbetsworth** [comment]
I can confirm I'm now able to see the points when there is no audio associated with the peaks instance.

Thanks again!
