### ISSUE TITLE
Playhead text background color

### ISSUE THREAD

**Issue by amber-huo** [bbc/peaks.js#507]
Hi, I would like to be able to customize a background/highlighted color to the playhead text. If the waveform and playhead text happen to be similarly colored, the text doesn't show up very well when it overlaps high amplitude areas. So it's for better color contrast/generally more visible text. Something like:
![image](https://github.com/bbc/peaks.js/assets/105802812/efa5bac2-9c63-4420-92c7-616d2f327e29)

**Comment by chrisn** [comment]
Thanks for this suggestion. It sounds good, we could add an option for the background color and possibly also for padding around the text.

**Comment by amber-huo** [comment]
Thanks @chrisn, I opened a PR for both background color and padding around the text, like so:
![image](https://github.com/bbc/peaks.js/assets/105802812/4265b3fa-d409-4376-b187-69430064862b)

**Comment by chrisn** [comment]
Your PR is now merged. Thanks again for contributing! 🙏

**Comment by chrisn** [comment]
@amber-huo I have just released v3.2.0 which includes your PR.
