### ISSUE TITLE
"This waveform data version not supported"

### ISSUE THREAD

**Issue by WilliamHayward108** [bbc/peaks.js#510]
I'm current hitting this error in the Waveformdata.create function. I am passing a datauri as my waveform source, the .json that is being passed is 

`{"version":2,"channels":1,"sample_rate":44100,"samples_per_pixel":256,"bits":8,"length":2611,"data":[0,0,0,0,0]}`

I've shortened the data array for the purposes of making this issue, the version is '2' which from what I can see is supported by peaks so I'm not too sure what the issue is

**Comment by chrisn** [comment]
Your example file looks OK. Are you using the `json` option when you can `Peaks.init()` ? You'll get this error if you use `arraybuffer`.

```
dataUri: {
  json: '/v2.json'
},
```

**Comment by WilliamHayward108** [comment]
That was it, a silly oversight on my part. Thanks!
