### ISSUE TITLE
transparent waveformColor when using playedWaveformColor in configuration

### ISSUE THREAD

**Issue by EZWrighter** [bbc/peaks.js#511]
Using this in the configuration causes the waveform to be transparent or white, matching the background.  I expect it to change the main waveform green and the played track muted green.

```
options = {
                      overview: {
                        container: document.getElementById('audio-audio-levels'),
                        waveformColor: 'rgba(116, 183, 0, .2)',
                        playedWaveformColor: 'rgba(116,183,0,.5)'
                      },
                      mediaElement: document.getElementById('visual-preview-video').querySelector("video"),
                      dataUri: {
                        arraybuffer: URIofLevels
                      }
};
```

If I remove the playedWaveformColor from the configuration, it shows the waveform as the green I would expect.

Thanks.

**Comment by chrisn** [comment]
Those options give me this, is this not what you expect?

![image](https://github.com/bbc/peaks.js/assets/57790/bf600bcf-240f-4ebd-b207-b40dee6bfdb4)

**Comment by EZWrighter** [comment]
Nope, when used in my application, I see this: 
![image](https://github.com/bbc/peaks.js/assets/466883/e936686c-253f-4c83-9bb1-aad010f8e002)

I did reduce this down with almost an identical setup and cannot reproduce the problem in the reduced case, so it has to be my configuration, but no clue as to why.  In my app I have 2 waveforms sharing the same video element as their controller.  If you have any pointers that might help resolve, great...otherwise I will keep digging.

Thanks.

**Comment by EZWrighter** [comment]
Interesting....has something to do with using videojs and grabbing the video element and setting that as the mediaElement for peaks.js initialization.  Still tracking it down :-D

**Comment by chrisn** [comment]
Did you find out what's happening?

**Comment by EZWrighter** [comment]
> Did you find out what's happening?
No, I had to give up on the color issue and not use a playedWaveformColor, but thanks for checking in  :-(  I think it might have something to do with my use of the video element from videojs and the callbacks.   I re-use the same video player and change out the source content when switching context in my app, but create a new peak instance to display the levels for each of the new source.  Shrug.  I am fine if you want to close this out as I can't give you a reproducible test.

**Comment by chrisn** [comment]
OK, if there's anything I do to investigate, let me know.

**Comment by deopard** [comment]
I experienced the same issue. In my case, I was using an audioBuffer sourced from elsewhere rather than fetching it from URL. The problem arose because I hadn't set up the externalPlayer. Alongside this, some other functionalities were also not working properly. After configuring the externalPlayer, everything started working as expected.
