### ISSUE TITLE
Points are misaligned with the waveform when using seconds for zooming

### ISSUE THREAD

**Issue by stepanmk** [bbc/peaks.js#513]
Hi,

I'm using peaks.js in my web application, and when using predefined `zoomLevels` such as `[512, 1024, 2048, 4096]`, everything seems to be working well, as shown in the first clip. The points (annotated measure positions) are aligned with the waveform at each zoom level (I'm using a scroll wheel to switch between the different zoom levels).

https://github.com/bbc/peaks.js/assets/63413990/ee06e90d-8667-411f-a25a-a97b25388f99

However, when I want to use `view.setZoom({seconds: someValue})`, the points get randomly misaligned with different values of the `seconds` parameter. This is shown in the second clip. In this case, each scroll wheel step corresponded to either subtraction or addition of 5 seconds to a variable that I use to set the new value for the  `seconds` parameter.

https://github.com/bbc/peaks.js/assets/63413990/250fd016-3186-418d-8c7b-8233fd70c468

The misalignment is also apparent when adding segments to the waveform. It seems like the points and segments are aligned well with the time stamps of the timeline and only the waveform itself gets misaligned when using seconds for zooming. It also happened when I tried incrementing or decrementing the  `seconds` by a different amount of seconds. Interestingly, the misalignment gets progressively worse at the later parts of the waveform (towards the end of the audio file).

Furthermore, I tried using predefined `zoomLevels` that are not powers of two, and it also worked as expected. I suppose there is a problem with resampling the waveform view when using arbitrary values in seconds for zooming. I can get around this problem by sticking with precomputed `zoomLevels`, but I also need to use zooming by seconds in the other parts of the app I'm developing. 

I'm using [audiowaveform](https://github.com/bbc/audiowaveform) to precompute the waveforms with the `-z` parameter set to 32, but changing it does not seem to affect anything in terms of the alignment. Also, I'm working with files with a sampling rate of 44.1 kHz. I hope there is not anything wrong on my end.

Thanks,
Stepan

**Comment by chrisn** [comment]
Thank you, and particularly for the detailed write-up and videos 🙏 I'll investigate ... I'm not sure this is entirely caused by the `seconds` zoom level, I'm able to reproduce still using the default power-of-two zoom levels.

**Comment by chrisn** [comment]
This is fixed now, see the above commit and [changelog](https://github.com/bbc/peaks.js/blob/master/CHANGELOG.md#321-20231129) for details. Thank you again for reporting this.

**Comment by stepanmk** [comment]
Thanks for the quick fix, I can confirm that it now works as expected.
