### ISSUE TITLE
Some audio can not peak.init,no error message

### ISSUE THREAD

**Issue by yg2342423523** [bbc/peaks.js#523]
Hello,sir.I recently use peak.js to generate waves,but some of my audio can not work,i use this audio and this json file,i try some ways,only when i change it to mp3 can be work,i think my wav audio is ok,because it can be played ,downloaded and work well in web.Can you help me this?What wrong with this type of audio?I have huge of this,change format is not good;
[病人咳嗽.json](https://github.com/bbc/peaks.js/files/14162066/default.json)
[病人咳嗽.zip](https://github.com/bbc/peaks.js/files/14162073/default.zip)

**Comment by chrisn** [comment]
This is an ADPCM format WAV file, and it appears that browsers don't support this format (HTMLAudioElement or Web Audio `decodeAudioData`). I get this error in Firefox:

> Media resource [url] could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006)

Can you convert the files to PCM format?

**Comment by chrisn** [comment]
I've added code to check for this error condition, so now `Peaks.init()` will report the error, rather than failing silently.

I'll close the issue, as there's nothing more we can do here.
