### ISSUE TITLE
Change width of playhead line

### ISSUE THREAD

**Issue by AngelCamargo404** [bbc/peaks.js#529]
How can I change the width of the playhead line? It is specifically the line that shows when I click.
![playhead line image](https://github.com/bbc/peaks.js/assets/78267694/6ed49812-6097-43fb-83c2-5310e8aaf9c6)

**Comment by chrisn** [comment]
Thanks - the width was hard-coded, so I've just added an option, `playheadWidth` that lets you control it.

**Comment by AngelCamargo404** [comment]
Thank you Chris!

**Comment by chrisn** [comment]
Thanks, it was a simple change so I just did it. It's available in the new v3.4.0 release.
