### ISSUE TITLE
Issue with current time.

### ISSUE THREAD

**Issue by vivekd95** [bbc/peaks.js#530]
Hi @chrisn 

When working with zoomview, a new issue is found (checked in the latest release). The current time is getting rounded off (to the ceiling value) when the value after 3 decimals starts with 9 like 0.346999. This value will get rounded off to 0.347 when we use `player.getCurrentTime()` while on zoomview it will show the value before rounding off. Please take a look at the screenshots I've attached below.

**Screenshot of Chrome's console**
![Screenshot from 2024-06-13 12-36-38](https://github.com/bbc/peaks.js/assets/107407402/fbb8d3be-7bb9-416e-9a81-449496a80317)

**Screenshot of the zoomview**
![Screenshot from 2024-06-13 12-36-16](https://github.com/bbc/peaks.js/assets/107407402/da61e634-ecf1-48ed-8e0a-ee7b2d7523bf)

**Comment by chrisn** [comment]
The code intentionally floors (i.e., rounds towards zero), so in your example 0.346999 will display as 0.346.

**Comment by chrisn** [comment]
What you're seeing is the effect of different floating point rounding implementations, when converting a floating point number to a string. Peaks.js does it one way, the browser console does it differently. The underlying value is still the same, though, and there's no loss of precision.

**Comment by vivekd95** [comment]
So, the value that I am getting should be the same? If yes, I tried several more things and discovered these screenshot values.

**Screenshot of Chrome's console**
![image_2024_06_14T06_10_54_601Z](https://github.com/bbc/peaks.js/assets/107407402/c5962fae-cc83-4f73-979c-ca5c78494c79)

**Screenshot of zoomview**
![image_2024_06_14T06_10_26_398Z](https://github.com/bbc/peaks.js/assets/107407402/1cc4024d-871d-4226-be1a-59601e1bda8d)

**Screenshot of the event triggered**
![image_2024_06_14T06_09_55_652Z](https://github.com/bbc/peaks.js/assets/107407402/61c505a6-b5a8-431a-9c50-facd8ddbd722)

So, is the console showing 2 at the end from the browser's side? The main issue that I am facing is getting the difference of 0.001 when I create in my example.

**Comment by chrisn** [comment]
> So, the value that I am getting should be the same? 

No, I wouldn't expect the values to be the same, because the Peaks.js library uses a different algorithm to convert the number to a string than the browser console.

The [`formatPlayheadTime`](https://github.com/bbc/peaks.js/blob/master/doc/customizing.md#time-labels) option allows you to format the value differently, if you want to.

**Comment by chrisn** [comment]
I'll close this, but please re-open if you think more discussion or changes are needed.
