### ISSUE TITLE
Question: waveform data 

### ISSUE THREAD

**Issue by jason30704** [bbc/peaks.js#532]
Hello,
According to the example code over there at peaksjs-react-example (https://github.com/chrisn/peaksjs-react-example),
I know that we can use 07030039.dat to draw a waveform.

If I want to draw a wave without a .dat file, how can I let the program use audio to generate an object that allows peaks to draw a wave?
I have tried to use arraybuffer or waveform (as shown below) to initial(), but I will get errors such as "waveform data version not supported" and so on.
![image](https://github.com/user-attachments/assets/84072961-72e4-487c-b947-c96832e6b961)

PS: I also tried to use Audio context to initial(), and it works. As shown below. However, if the audio is too large, each render will take a lot of time.
![image](https://github.com/user-attachments/assets/a31f0cec-339a-4995-9b74-390d6607437c)

**Comment by chrisn** [comment]
Does the documentation at https://github.com/bbc/peaks.js/blob/master/README.md#generating-waveform-data help answer your question?

>  will get errors such as "waveform data version not supported" and so on.

You might see this error if you provide JSON format waveform data that doesn't have the expected structure.

**Comment by jason30704** [comment]
Thanks for your response.
I would like to know if peaks.js can draw wave based on the buffer or waveform in the code below? Or can I use them to get the data in the correct format to initail peaks?

> ![image](https://private-user-images.githubusercontent.com/52276669/355780852-84072961-72e4-487c-b947-c96832e6b961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNzk3OTEsIm5iZiI6MTcyMzA3OTQ5MSwicGF0aCI6Ii81MjI3NjY2OS8zNTU3ODA4NTItODQwNzI5NjEtNzJlNC00ODdjLWI5NDctYzk2ODMyZTZiOTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAxMTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmODM5Yjk3MzUyZDE0MmU3ZTgxZmIzYTdjZTE0Y2U3ODFjNzc5ODdhZTFmNTNlMGFjZTUyZWI3ZjZlNjI2M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CRufgUwG22NC06fE9UieNvleDE7mVQXw9bp5XXMxRf4)
> 
I wrote this code with reference to https://github.com/bbc/waveform-data.js.

**Comment by jason30704** [comment]
Maybe this example can express my problem better.
I want to draw a wave when there is only audio file or audio arraybuffer.
But in the picture below, the left case can draw the wave correctly, but the right case cannot draw the wave.
![image](https://github.com/user-attachments/assets/0c5cd026-329e-4a51-9e74-a2e3c4204d0b)

**Comment by chrisn** [comment]
You can use `waveform.toArrayBuffer()` to give you the data to pass to `Peaks.init()`:

```js
fetch("/07030039.mp3")
  .then((response) => {
    return response.arrayBuffer();
  })
  .then((buffer) => {
    const options = {
      audio_context: new AudioContext(),
      array_buffer: buffer,
      scale: 128
    };
    
    WaveformData.createFromAudio(options, (err, waveform) => {
      Peaks.init({
        zoomview: { ... },
        overview: { ... },
        mediaElement: audioElement,
        waveformData: {
          arraybuffer: waveform.toArrayBuffer()
        },
        zoomLevels: [128, 256, 512, 1024]
      }, (err, peaks) => {
        console.log("Peaks instance ready");
      });
    });
  });
```

But you don't need to do the fetch yourself, Peaks.js will do it for you, using the source set on the audio element:

```html
<audio controls="controls">
  <source src="/07030039.mp3" type="audio/mpeg">
</audio>
```

```js
Peaks.init({
  zoomview: { ... },
  overview: { ... },
  mediaElement: audioElement,
  webaudio: {
    audioContext: new AudioContext(),
  },
  zoomLevels: [128, 256, 512, 1024]
}, (err, peaks) => {
  console.log("Peaks instance ready");
});
```

**Comment by jason30704** [comment]
Thank you very much for your patient answer, you have answered my questions a lot!

**Comment by jason30704** [comment]
Sorry, I'd like to ask one more question if I can.

I tried to use waveform.toArrayBuffer() to download the result of 07030039.mp3 into a .dat file. I noticed that the size of the downloaded file is smaller than the 07030039.dat provided on git.

However, both of them are no problem to use. I'm just curious what's the reason for this?
Can we control this size, or is there any concerns with this approach?

![image](https://github.com/user-attachments/assets/4bbd6d11-834f-4d61-a40f-59249be33918)

**Comment by chrisn** [comment]
If it's a small difference in size (a few bytes), it's probably because of differences between the MP3 decoder in your browser and the `audiowaveform` program I use. If it's a larger difference, it could be because you selected a different scale value to create the waveform see [this](https://github.com/bbc/waveform-data.js/blob/master/doc/API.md#waveformdatacreatedata) and the `zoomLevels` option in `Peaks.init()`. A smaller scale value results in a larger file size.
