### ISSUE TITLE
Get subWaveformData

### ISSUE THREAD

**Issue by jason30704** [bbc/peaks.js#538]
Hi chrisn,
I would like to know if waveformData has a way to cut out subwaveformData based on time intervals?

**Comment by chrisn** [comment]
Yes, have a look at [WaveformData.slice()](https://github.com/bbc/waveform-data.js/blob/master/doc/API.md#waveformDatasliceoptions).

Can I suggest please using Discussions for questions like this. I'd prefer to keep issues for bugs and feature requests.

**Comment by jason30704** [comment]
Sorry, I don't know that much about the interaction here yet.
I got it now, thanks.

**Comment by chrisn** [comment]
That's ok, your input and questions are very welcome!
