### ISSUE TITLE
Generating the waveform using multiple dat files

### ISSUE THREAD

**Issue by vivekd95** [bbc/peaks.js#542]
Hi 
Right now, I am generating the waveform from a single .dat file. Now, I want to generate the same waveform from multiple .dat files extracted from the same media file. Now, I want each dialogue in that media to have its separate .dat file, which I ultimately want to use to render the dialogues as segments on the waveform. Is there any way to do that?

**Comment by chrisn** [comment]
I'm not sure I understand fully. How do the .dat files relate to the media file? Are they from different audio tracks or channels within the media, so run concurrently, or from different time periods?

**Comment by vivekd95** [comment]
I am sorry for this confusion. 
Let me try to clear it up.

After extracting the mp3 from the mp4(the said media) I am using `audiowaveform` to create a binary waveform data file (.dat). Then, I used this created .dat file and sent it to `arraybuffer` to generate the waveform data.

**Comment by vivekd95** [comment]
Yeah but for this I need a single waveform URL, right? 
Let me explain my exact use case. I am trying to make a dubbing tool. Now for each dubbed dialogue, I need to add an individual segment that I want to get appended on the waveform one by one based on user action. Now for each dialogue, I have separate mp3 and binary waveform data files aka .dat file. Now, Suppose in the beginning I have only one dialogue which means I only have one .dat file. Now, If I want to add another dialogue which means I will have another .dat file that will create the waveform for that particular portion. I want to append this new waveform data part to the existing one. Do we have anything in peaks,js for this kind of functionality, or do I have to do it manually in any other way if possible?

**Comment by chrisn** [comment]
Yes, `setSource()` only lets you provide a single waveform, to go with a single audio file. So you'd have to do this manually. `setSource` allows you to provide your own `WaveformData` object, which could be constructed from others using the `concat` and `slice` methods, possibly. https://github.com/bbc/waveform-data.js/blob/master/doc/API.md

**Comment by vivekd95** [comment]
Also, Is it possible to generate waveform without peaks? If yes then how?

**Comment by chrisn** [comment]
I don't think so, currently. Maybe a solution could be to allow fully custom waveform rendering, then you could implement any rendering you like, including drawing nothing.
