### ISSUE TITLE
" peaks.segments.add(): startTime should not be negative " by insert-segment mode

### ISSUE THREAD

**Issue by jason30704** [bbc/peaks.js#545]
Hello,
I found that when using insert-segment mode, if you click close to the border, there is a chance that the following error may be triggered.

https://github.com/user-attachments/assets/09cf0dea-7102-4399-a0a0-5b1e8200b716

![image](https://github.com/user-attachments/assets/8afdbb27-42f8-4ddd-afcc-e3aa5f8c0674)

**Comment by chrisn** [comment]
This happens because MouseEvent [offsetX](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX) property can sometimes be -1. I'm not sure why this happens.

**Comment by chrisn** [comment]
This is fixed in v4.0.0-beta.0.
