### ISSUE TITLE
Cleanup the cyclic references variables

### ISSUE THREAD

**Issue by oncletom** [bbc/peaks.js#55]
- [ ] segments containing views containing segments
- [ ] points containing views containing points

**Comment by chrisn** [comment]
I agree, we should try to clean up the internal design, with a better separation of UI view logic from the waveform, segments, and points data.

**Comment by oncletom** [comment]
Yeah, to me the various modules should not be bound to peaks but rather be pure classes (no references to peaks as being `this`, explicit parameters etc.)

It should be easier to do with ES2015 classes and such (cf #128).

**Comment by oncletom** [comment]
Should be addressed by #87
