### ISSUE TITLE
preventDefault mouseUp event look like cause error on touch device

### ISSUE THREAD

**Issue by SimDaeSoo** [bbc/peaks.js#550]
In the mouse up function call preventDefault as follows.
The mouse up function seems to be throwing an error in preventDefault because the passive value is registered as true.
If you need a sample repository, I'll try to create one.
If you have a different way of handling it, I'd really appreciate your help.  

### Sample Video
https://github.com/user-attachments/assets/a917c544-588d-41e7-813f-7c9828392471

https://github.com/bbc/peaks.js/blob/e65c334d9c62660b6f285cf0e21b040182d66a58/src/mouse-drag-handler.js#L132-L159
```js
MouseDragHandler.prototype._mouseUp = function(event) {
  let clientX;

  if (event.type === 'touchend') {
    clientX = Math.floor(event.changedTouches[0].clientX);

    if (event.cancelable) {
      // this preventDefault function throw error
      event.preventDefault();
    }
  }
  else {
    clientX = Math.floor(event.clientX);
  }
  ...
};
```

https://github.com/bbc/peaks.js/blob/e65c334d9c62660b6f285cf0e21b040182d66a58/src/mouse-drag-handler.js#L94

**Comment by chrisn** [comment]
https://github.com/bbc/peaks.js/commit/3cf46b657cfbcf615341c638232b79acf4e8850d should fix this.
