### ISSUE TITLE
Suggestion: To add the option of playing the segment from the timestamp provided by the user

### ISSUE THREAD

**Issue by vivekd95** [bbc/peaks.js#557]
Hi @chrisn 
 
 There should be an option to pass the time to `instance.player.playSegment(segment)` so that we can play the segment from whatever timestamp we want to. Could you share your opinion?

**Comment by chrisn** [comment]
I think this is already possible, using code such as:

```js
peaksInstance.player.playSegment({ startTime: 5.0, endTime: 10.0 });
```

**Comment by vivekd95** [comment]
If you'd like, I can contribute to this suggestion.

**Comment by chrisn** [comment]
What are you suggesting? I'm not sure a change is needed, but the documentation could be improved.

**Comment by vivekd95** [comment]
My bad. I misread your comment as "can be possible" instead of "already possible".

Although, I tried implementing it but I was not able to.
```
let currentTime = peakInstance.player.getCurrentTime();
peakInstance.player.playSegment({ startTime: currentTime, endTime: segment.endTime });
```

Is there anything I am doing wrong? If so, please tell.

**Comment by chrisn** [comment]
Your example works for me, so I'm not sure.
