### ISSUE TITLE
Toggle a view on/off

### ISSUE THREAD

**Issue by oncletom** [bbc/peaks.js#59]

**Comment by chrisn** [comment]
See also #53. The refactoring done in the v0.9.0 release is a step towards enabling configurable views.

**Comment by chrisn** [comment]
The [Views API](https://github.com/bbc/peaks.js/blob/master/README.md#views-api) contains methods that allow applications to toggle the waveform views. See [demo/index.html](https://github.com/bbc/peaks.js/blob/master/demo/index.html) for an example.
