### ISSUE TITLE
Remove points/segments option in the constructor

### ISSUE THREAD

**Issue by oncletom** [bbc/peaks.js#61]
It adds unnecessary logic and can be performed as is:

``` js
Peaks.init({ … })
  .segments.add([ { startTime: 10, endTime: 12 } ])
  .points.add([ { timestamp: 11 } ]);
```

**Comment by chrisn** [comment]
I'd prefer not to introduce a breaking API change at this stage. However, `Peaks.init()` does take a lot of options in addition to the ones mentioned here, and we may want to look at simplifying this at some point.
