### ISSUE TITLE
Add Point Markers Individually

### ISSUE THREAD

**Issue by chainlink** [bbc/peaks.js#67]
We'd like to be able to set point markers per point (rather than globally for the whole waveform)

_Currently Implementing This feature_

**Comment by oncletom** [comment]
@chrisn I think that has been addressed in #137 and #141, isn't it?

**Comment by oncletom** [comment]
Should be addressed by #87.

**Comment by chrisn** [comment]
The marker customisation is improved in v0.18.0. I'll close this, please raise a new issue if further changes are needed.
