### ISSUE TITLE
Gaps between segments

### ISSUE THREAD

**Issue by summer1278** [bbc/peaks.js#68]
I tried some examples to fix the gaps between segments which looks like this:

```
[{"startTime":55.77,"endTime":58.1,"editable":false,"color":"rgba(215, 40, 40, 0.9)","labelText":"segment26"},
{"startTime":58.1,"endTime":60.42,"editable":false,"color":"rgba(215, 40, 40, 0.9)","labelText":"segment27"},
{"startTime":60.42,"endTime":62.74,"editable":false,"color":"rgba(215, 40, 40, 0.9)","labelText":"segment28"},
{"startTime":62.74,"endTime":65.06,"editable":false,"color":"rgba(215, 40, 40, 0.9)","labelText":"segment29"}]
```

So the first `endTime` is the same as second `startTime` here, background color is default to green, segments are red, but on the visualization on Peaks, there are still visible small gaps between them, may I ask does it design like this?

Screenshot:
![screenshot from 2014-07-15 01 28 07](https://cloud.githubusercontent.com/assets/6974397/3579102/4eae6de2-0bb7-11e4-8cbb-e7ad502fa1df.png)

**Comment by chrisn** [comment]
Just tested in the latest version, and this is working OK.
