### ISSUE TITLE
Method to destroy peaksInstance

### ISSUE THREAD

**Issue by bitwit** [bbc/peaks.js#69]
So we are currently using peaks.js in the context of a single page application and have situations where multiple peaksInstances can be created before a page reloads.

What we are seeing is that after loading the second peaks instance, any browser resizing crashes the tab. Note, we can load many peaks instances on top without issue but the browser resizing is what causes the crash. 

We suspect that we are creating memory leaks by not properly destroying a peaksInstance before replacing it and there are perhaps lingering callbacks that should be deregistered.

So this is sort of a feature request/request for guidance on how we might go about making sure peaks has completely cleared. There appears to be no peaks.destroy() method.

Much appreciated!

**Comment by oncletom** [comment]
@chrisn I guess this one can be closed since #150 was merged.
