### ISSUE TITLE
Local tests = OK - CI tests = timeout

### ISSUE THREAD

**Issue by oncletom** [bbc/peaks.js#83]
# Local tests

![screen shot 2014-09-15 at 11 45 06](https://cloud.githubusercontent.com/assets/138627/4270203/41b661f8-3cc7-11e4-8ded-ca02cb960df5.png)

``` bash
iectrl start 9
npm start

# in another terminal window
npm test
```
# Saucelabs tests

![screen shot 2014-09-15 at 11 57 37](https://cloud.githubusercontent.com/assets/138627/4270204/46778028-3cc7-11e4-8a26-d78ca1e6faf9.png)

``` bash
# run the sauce connect binary
# then:
npm start

# in another terminal window
CI=1 npm test
```

> https://travis-ci.org/bbcrd/peaks.js/builds/35322449
> https://travis-ci.org/bbcrd/peaks.js/builds/35622630

**Comment by chrisn** [comment]
Closing, as the Travis CI build is working fine as it is.
