### ISSUE TITLE
Incorrect behaviour when dragging zoom view

### ISSUE THREAD

**Issue by lowpitch** [bbc/peaks.js#90]
Found some incorrect behaviour in the current demo page:
- Press button to create Segment at current time
- Press button Zoom out
- Drag zoom view
- Segments and time markers drag correctly, but the waveform view in the background does not move. The master waveform is then out of sync with the segments

I will have a look at this problem while making other changes.

**Comment by chrisn** [comment]
The zooming and scrolling behaviour is fixed in [v0.9.0](https://github.com/bbc/peaks.js/releases/tag/v0.9.0).
