### ISSUE TITLE
Right click context menu

### ISSUE THREAD

**Issue by chainlink** [bbc/peaks.js#97]
We'd like the ability to right click on points or segments to add or remove them. Any thoughts on how this might be accomplished?

**Comment by oncletom** [comment]
Rethinking about it, this could be done as simply as:

```js
const p = Peaks.init({ ... });

p.waveforms.waveformOverview.on('contextmenu', () => {
  // ...
});
```

See http://konvajs.github.io/docs/events/Binding_Events.html. `contextmenu` is not mentioned but should work as I see references to it in Konva codebase.

**Comment by chrisn** [comment]
Peaks,js now surfaces `contextmenu` events, so applications can use this to show their own context menu outside of Peaks.js. Please re-open if there's need for Peaks.js to display the context menu itself.
